	const_def
	const JOHTO_REGION
	const KANTO_REGION
	const ORANGE_REGION


	const_def

	const SPECIAL_MAP        ; 00

	const DANIELS_TOWN
	const ASAOKA_CITY
	const KIKUNO_TOWN
	const BREGUET_RUINS
	const HETZELTRON
	const HATTORI_VILLAGE
	const OUEST_PATHWAY
	const CENDRE_LOWLAND
	const MT_INDUCTOR
	const MT_INDUCTOR_CALDERA
	const MINAMI_WETLANDS
	const SYLVAN_TRAIL
	const GELID_RAVINE
	const TANI_RIVER_1
	const TANI_RIVER_2
	const CRYSTALINE_LAKE_1
	const CRYSTALINE_LAKE_2

LANDMARK_LIMIT EQU const_value + -1	

KANTO_LANDMARK EQU const_value



SHAMOUTI_LANDMARK EQU const_value



NUM_LANDMARKS EQU const_value
