AlolaAnimationPointers::
	add_anim Rowlet
	add_anim Dartrix
	add_anim Decidueye
	add_anim Litten
	add_anim Torracat
	add_anim Incineroar
	add_anim Popplio
	add_anim Brione
	add_anim Primarina
	add_anim Pikipeck
	add_anim Trumbeak
	add_anim Toucannon
	add_anim Yungoos
	add_anim Gumshoos
	add_anim Grubbin
	add_anim Charjabug
	add_anim Vikavolt
	add_anim Crabrawler
	add_anim Crabominable
	add_anim Oricorio
	add_anim Cutiefly
	add_anim Ribombee
	add_anim Rockruff
	add_anim Lycanroc
	add_anim Wishiwashi
	add_anim Mareanie
	add_anim Toxapex
	add_anim Mudbray
	add_anim Mudsdale
	add_anim Dewpider
	add_anim Araquanid
	add_anim Fomantis
	add_anim Lurantis
	add_anim Morelull
	add_anim Shiinotic
	add_anim Salandit
	add_anim Salazzle
	add_anim Stufful
	add_anim Bewear
	add_anim Bounsweet
	add_anim Steenee
	add_anim Tsareena
	add_anim Comfey
	add_anim Oranguru
	add_anim Passimian
	add_anim Wimpod
	add_anim Golisopod
	add_anim Sandygast
	add_anim Pallossand
	add_anim Pyukumuku
	add_anim Type_null
	add_anim Silvally
	add_anim Minior
	add_anim Komala
	add_anim Turtonator
	add_anim Togedemaru
	add_anim Mimikyu
	add_anim Bruxish
	add_anim Drampa
	add_anim Dhelmise
	add_anim Jangmo_o
	add_anim Hakamo_o
	add_anim Kommo_o
	add_anim Tapu_koko
	add_anim Tapu_lele
	add_anim Tapu_bulu
	add_anim Tapu_fini
	add_anim Cosmog
	add_anim Cosmoem
	add_anim Solgaleo
	add_anim Lunala
	add_anim Nihilego
	add_anim Buzzswole
	add_anim Pheromosa
	add_anim Xurkitree
	add_anim Celesteela
	add_anim Kartana
	add_anim Guzzlord
	add_anim Necrozma
	add_anim Magearna
	add_anim Marshadow
	add_anim Poipole
	add_anim Naganadel
	add_anim Stakataka
	add_anim Blacephalon
	add_anim Zeraora
	add_anim Meltan
	add_anim Melmetal
