AlolaFramesPointers::
	add_frames Rowlet
	add_frames Dartrix
	add_frames Decidueye
	add_frames Litten
	add_frames Torracat
	add_frames Incineroar
	add_frames Popplio
	add_frames Brione
	add_frames Primarina
	add_frames Pikipeck
	add_frames Trumbeak
	add_frames Toucannon
	add_frames Yungoos
	add_frames Gumshoos
	add_frames Grubbin
	add_frames Charjabug
	add_frames Vikavolt
	add_frames Crabrawler
	add_frames Crabominable
	add_frames Oricorio
	add_frames Cutiefly
	add_frames Ribombee
	add_frames Rockruff
	add_frames Lycanroc
	add_frames Wishiwashi
	add_frames Mareanie
	add_frames Toxapex
	add_frames Mudbray
	add_frames Mudsdale
	add_frames Dewpider
	add_frames Araquanid
	add_frames Fomantis
	add_frames Lurantis
	add_frames Morelull
	add_frames Shiinotic
	add_frames Salandit
	add_frames Salazzle
	add_frames Stufful
	add_frames Bewear
	add_frames Bounsweet
	add_frames Steenee
	add_frames Tsareena
	add_frames Comfey
	add_frames Oranguru
	add_frames Passimian
	add_frames Wimpod
	add_frames Golisopod
	add_frames Sandygast
	add_frames Pallossand
	add_frames Pyukumuku
	add_frames Type_null
	add_frames Silvally
	add_frames Minior
	add_frames Komala
	add_frames Turtonator
	add_frames Togedemaru
	add_frames Mimikyu
	add_frames Bruxish
	add_frames Drampa
	add_frames Dhelmise
	add_frames Jangmo_o
	add_frames Hakamo_o
	add_frames Kommo_o
	add_frames Tapu_koko
	add_frames Tapu_lele
	add_frames Tapu_bulu
	add_frames Tapu_fini
	add_frames Cosmog
	add_frames Cosmoem
	add_frames Solgaleo
	add_frames Lunala
	add_frames Nihilego
	add_frames Buzzswole
	add_frames Pheromosa
	add_frames Xurkitree
	add_frames Celesteela
	add_frames Kartana
	add_frames Guzzlord
	add_frames Necrozma
	add_frames Magearna
	add_frames Marshadow
	add_frames Poipole
	add_frames Naganadel
	add_frames Stakataka
	add_frames Blacephalon
	add_frames Zeraora
	add_frames Meltan
	add_frames Melmetal
