AlolaAnimationIdlePointers::
	add_idleanim Rowlet
	add_idleanim Dartrix
	add_idleanim Decidueye
	add_idleanim Litten
	add_idleanim Torracat
	add_idleanim Incineroar
	add_idleanim Popplio
	add_idleanim Brione
	add_idleanim Primarina
	add_idleanim Pikipeck
	add_idleanim Trumbeak
	add_idleanim Toucannon
	add_idleanim Yungoos
	add_idleanim Gumshoos
	add_idleanim Grubbin
	add_idleanim Charjabug
	add_idleanim Vikavolt
	add_idleanim Crabrawler
	add_idleanim Crabominable
	add_idleanim Oricorio
	add_idleanim Cutiefly
	add_idleanim Ribombee
	add_idleanim Rockruff
	add_idleanim Lycanroc
	add_idleanim Wishiwashi
	add_idleanim Mareanie
	add_idleanim Toxapex
	add_idleanim Mudbray
	add_idleanim Mudsdale
	add_idleanim Dewpider
	add_idleanim Araquanid
	add_idleanim Fomantis
	add_idleanim Lurantis
	add_idleanim Morelull
	add_idleanim Shiinotic
	add_idleanim Salandit
	add_idleanim Salazzle
	add_idleanim Stufful
	add_idleanim Bewear
	add_idleanim Bounsweet
	add_idleanim Steenee
	add_idleanim Tsareena
	add_idleanim Comfey
	add_idleanim Oranguru
	add_idleanim Passimian
	add_idleanim Wimpod
	add_idleanim Golisopod
	add_idleanim Sandygast
	add_idleanim Pallossand
	add_idleanim Pyukumuku
	add_idleanim Type_null
	add_idleanim Silvally
	add_idleanim Minior
	add_idleanim Komala
	add_idleanim Turtonator
	add_idleanim Togedemaru
	add_idleanim Mimikyu
	add_idleanim Bruxish
	add_idleanim Drampa
	add_idleanim Dhelmise
	add_idleanim Jangmo_o
	add_idleanim Hakamo_o
	add_idleanim Kommo_o
	add_idleanim Tapu_koko
	add_idleanim Tapu_lele
	add_idleanim Tapu_bulu
	add_idleanim Tapu_fini
	add_idleanim Cosmog
	add_idleanim Cosmoem
	add_idleanim Solgaleo
	add_idleanim Lunala
	add_idleanim Nihilego
	add_idleanim Buzzswole
	add_idleanim Pheromosa
	add_idleanim Xurkitree
	add_idleanim Celesteela
	add_idleanim Kartana
	add_idleanim Guzzlord
	add_idleanim Necrozma
	add_idleanim Magearna
	add_idleanim Marshadow
	add_idleanim Poipole
	add_idleanim Naganadel
	add_idleanim Stakataka
	add_idleanim Blacephalon
	add_idleanim Zeraora
	add_idleanim Meltan
	add_idleanim Melmetal
