AlolaBitmasksPointers::
	add_bitmasks Rowlet
	add_bitmasks Dartrix
	add_bitmasks Decidueye
	add_bitmasks Litten
	add_bitmasks Torracat
	add_bitmasks Incineroar
	add_bitmasks Popplio
	add_bitmasks Brione
	add_bitmasks Primarina
	add_bitmasks Pikipeck
	add_bitmasks Trumbeak
	add_bitmasks Toucannon
	add_bitmasks Yungoos
	add_bitmasks Gumshoos
	add_bitmasks Grubbin
	add_bitmasks Charjabug
	add_bitmasks Vikavolt
	add_bitmasks Crabrawler
	add_bitmasks Crabominable
	add_bitmasks Oricorio
	add_bitmasks Cutiefly
	add_bitmasks Ribombee
	add_bitmasks Rockruff
	add_bitmasks Lycanroc
	add_bitmasks Wishiwashi
	add_bitmasks Mareanie
	add_bitmasks Toxapex
	add_bitmasks Mudbray
	add_bitmasks Mudsdale
	add_bitmasks Dewpider
	add_bitmasks Araquanid
	add_bitmasks Fomantis
	add_bitmasks Lurantis
	add_bitmasks Morelull
	add_bitmasks Shiinotic
	add_bitmasks Salandit
	add_bitmasks Salazzle
	add_bitmasks Stufful
	add_bitmasks Bewear
	add_bitmasks Bounsweet
	add_bitmasks Steenee
	add_bitmasks Tsareena
	add_bitmasks Comfey
	add_bitmasks Oranguru
	add_bitmasks Passimian
	add_bitmasks Wimpod
	add_bitmasks Golisopod
	add_bitmasks Sandygast
	add_bitmasks Pallossand
	add_bitmasks Pyukumuku
	add_bitmasks Type_null
	add_bitmasks Silvally
	add_bitmasks Minior
	add_bitmasks Komala
	add_bitmasks Turtonator
	add_bitmasks Togedemaru
	add_bitmasks Mimikyu
	add_bitmasks Bruxish
	add_bitmasks Drampa
	add_bitmasks Dhelmise
	add_bitmasks Jangmo_o
	add_bitmasks Hakamo_o
	add_bitmasks Kommo_o
	add_bitmasks Tapu_koko
	add_bitmasks Tapu_lele
	add_bitmasks Tapu_bulu
	add_bitmasks Tapu_fini
	add_bitmasks Cosmog
	add_bitmasks Cosmoem
	add_bitmasks Solgaleo
	add_bitmasks Lunala
	add_bitmasks Nihilego
	add_bitmasks Buzzswole
	add_bitmasks Pheromosa
	add_bitmasks Xurkitree
	add_bitmasks Celesteela
	add_bitmasks Kartana
	add_bitmasks Guzzlord
	add_bitmasks Necrozma
	add_bitmasks Magearna
	add_bitmasks Marshadow
	add_bitmasks Poipole
	add_bitmasks Naganadel
	add_bitmasks Stakataka
	add_bitmasks Blacephalon
	add_bitmasks Zeraora
	add_bitmasks Meltan
	add_bitmasks Melmetal
