BitmasksPointers:
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw ZoruaBitmasks
	dw ZoroarkBitmasks
	dw RockruffBitmasks
	dw LycanrocBitmasks
	dw MimikyuBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw RotomBitmasks
	dw ChinglingBitmasks
	dw ChimechoBitmasks
	dw EspurrBitmasks
	dw Meowstic_MBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw DittoBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw VulpixBitmasks
	dw MukBitmasks
	dw Nidoran_MBitmasks
	dw NidorinoBitmasks
	dw NidorinaBitmasks
	dw NidokingBitmasks
	dw NidoqueenBitmasks
	dw SeviperBitmasks
	dw ZangooseBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw MienfooBitmasks
	dw MienshaoBitmasks
	dw HawluchaBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	dw FlabebeBitmasks
	dw FloetteBitmasks
	dw FlorgesBitmasks
	dw IgglybuffBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ChespinBitmasks
	dw QuilladinBitmasks
	dw ChesnaughtBitmasks
	dw DeerlingBitmasks
	dw SawsbuckBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw FoongusBitmasks
	dw AmoongussBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw PassimianBitmasks
	dw StuffulBitmasks
	dw BewearBitmasks
	dw GirafarigBitmasks
	dw HeracrossBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw MorelullBitmasks
	dw ShiinoticBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw SandileBitmasks
	dw KrokorokBitmasks
	dw KrookodileBitmasks
	dw TympoleBitmasks
	dw PalpitoadBitmasks
	dw SeismitoadBitmasks
	dw DrampaBitmasks
	dw GoomyBitmasks
	dw SliggooBitmasks
	dw GoodraBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OshawottBitmasks
	dw DewottBitmasks
	dw SamurottBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw AzurillBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw LaprasBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw DewpiderBitmasks
	dw AraquanidBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw FinneonBitmasks
	dw LumineonBitmasks
	dw QwilfishBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw StunfiskBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw TyrogueBitmasks
	dw HitmonchanBitmasks
	dw HitmonleeBitmasks
	dw HitmontopBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw MedititeBitmasks
	dw MedichamBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw FerroseedBitmasks
	dw FerrothornBitmasks
	dw ShuckleBitmasks
	dw NosepassBitmasks
	dw ProbopassBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw NoibatBitmasks
	dw NoivernBitmasks
	dw DruddigonBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw HaxorusBitmasks
	dw Jangmo_oBitmasks
	dw Hakamo_oBitmasks
	dw Kommo_oBitmasks
	dw DeinoBitmasks
	dw ZweilousBitmasks
	dw HydreigonBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw LittenBitmasks
	dw TorracatBitmasks
	dw IncineroarBitmasks
	dw FennekinBitmasks
	dw BraixenBitmasks
	dw DelphoxBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw FletchlingBitmasks
	dw FletchinderBitmasks
	dw TalonflameBitmasks
	dw HeatmorBitmasks
	dw DurantBitmasks
	dw ArchenBitmasks
	dw ArcheopsBitmasks
	dw RoggenrolaBitmasks
	dw BoldoreBitmasks
	dw GigalithBitmasks
	dw CarbinkBitmasks
	dw AmauraBitmasks
	dw AurorusBitmasks
	dw SneaselBitmasks
	dw WeavileBitmasks
	dw CryogonalBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FrosslassBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw UnownABitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw SigilyphBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw HonedgeBitmasks
	dw DoubladeBitmasks
	dw AegislashBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw YamaskBitmasks
	dw CofagrigusBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw SpiritombBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw SuicuneBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw LatiasBitmasks
	dw LatiosBitmasks
	dw SilvallyBitmasks
	dw MagearnaBitmasks
	dw ShayminBitmasks
	dw CelebiBitmasks
	dw ZygardeBitmasks
	dw MewBitmasks
	dw MewtwoBitmasks

