AnimationIdlePointers:
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw SylveonAnimationIdle
	dw ZoruaAnimationIdle
	dw ZoroarkAnimationIdle
	dw RockruffAnimationIdle
	dw LycanrocAnimationIdle
	dw MimikyuAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MagnezoneAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw PorygonZAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw RotomAnimationIdle
	dw ChinglingAnimationIdle
	dw ChimechoAnimationIdle
	dw EspurrAnimationIdle
	dw Meowstic_MAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw DittoAnimationIdle
	dw PurrloinAnimationIdle
	dw LiepardAnimationIdle
	dw VulpixAnimationIdle
	dw MukAnimationIdle
	dw Nidoran_MAnimationIdle
	dw NidorinoAnimationIdle
	dw NidorinaAnimationIdle
	dw NidokingAnimationIdle
	dw NidoqueenAnimationIdle
	dw SeviperAnimationIdle
	dw ZangooseAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw MienfooAnimationIdle
	dw MienshaoAnimationIdle
	dw HawluchaAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	dw FlabebeAnimationIdle
	dw FloetteAnimationIdle
	dw FlorgesAnimationIdle
	dw IgglybuffAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ChespinAnimationIdle
	dw QuilladinAnimationIdle
	dw ChesnaughtAnimationIdle
	dw DeerlingAnimationIdle
	dw SawsbuckAnimationIdle
	dw CottoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw FoongusAnimationIdle
	dw AmoongussAnimationIdle
	dw PhantumpAnimationIdle
	dw TrevenantAnimationIdle
	dw BonslyAnimationIdle
	dw SudowoodoAnimationIdle
	dw PassimianAnimationIdle
	dw StuffulAnimationIdle
	dw BewearAnimationIdle
	dw GirafarigAnimationIdle
	dw HeracrossAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw JoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw VenipedeAnimationIdle
	dw WhirlipedeAnimationIdle
	dw ScolipedeAnimationIdle
	dw MorelullAnimationIdle
	dw ShiinoticAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw SandileAnimationIdle
	dw KrokorokAnimationIdle
	dw KrookodileAnimationIdle
	dw TympoleAnimationIdle
	dw PalpitoadAnimationIdle
	dw SeismitoadAnimationIdle
	dw DrampaAnimationIdle
	dw GoomyAnimationIdle
	dw SliggooAnimationIdle
	dw GoodraAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OshawottAnimationIdle
	dw DewottAnimationIdle
	dw SamurottAnimationIdle
	dw BuizelAnimationIdle
	dw FloatzelAnimationIdle
	dw AzurillAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw LaprasAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw DewpiderAnimationIdle
	dw AraquanidAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw FinneonAnimationIdle
	dw LumineonAnimationIdle
	dw QwilfishAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw StunfiskAnimationIdle
	dw DwebbleAnimationIdle
	dw CrustleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmonchanAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmontopAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw MedititeAnimationIdle
	dw MedichamAnimationIdle
	dw SnoverAnimationIdle
	dw AbomasnowAnimationIdle
	dw FerroseedAnimationIdle
	dw FerrothornAnimationIdle
	dw ShuckleAnimationIdle
	dw NosepassAnimationIdle
	dw ProbopassAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw NoibatAnimationIdle
	dw NoivernAnimationIdle
	dw DruddigonAnimationIdle
	dw AxewAnimationIdle
	dw FraxureAnimationIdle
	dw HaxorusAnimationIdle
	dw Jangmo_oAnimationIdle
	dw Hakamo_oAnimationIdle
	dw Kommo_oAnimationIdle
	dw DeinoAnimationIdle
	dw ZweilousAnimationIdle
	dw HydreigonAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw LittenAnimationIdle
	dw TorracatAnimationIdle
	dw IncineroarAnimationIdle
	dw FennekinAnimationIdle
	dw BraixenAnimationIdle
	dw DelphoxAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw FletchlingAnimationIdle
	dw FletchinderAnimationIdle
	dw TalonflameAnimationIdle
	dw HeatmorAnimationIdle
	dw DurantAnimationIdle
	dw ArchenAnimationIdle
	dw ArcheopsAnimationIdle
	dw RoggenrolaAnimationIdle
	dw BoldoreAnimationIdle
	dw GigalithAnimationIdle
	dw CarbinkAnimationIdle
	dw AmauraAnimationIdle
	dw AurorusAnimationIdle
	dw SneaselAnimationIdle
	dw WeavileAnimationIdle
	dw CryogonalAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw FrosslassAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw UnownAAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw SigilyphAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw GolettAnimationIdle
	dw GolurkAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw HonedgeAnimationIdle
	dw DoubladeAnimationIdle
	dw AegislashAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw YamaskAnimationIdle
	dw CofagrigusAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw SpiritombAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw DusknoirAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw SuicuneAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw SilvallyAnimationIdle
	dw MagearnaAnimationIdle
	dw ShayminAnimationIdle
	dw CelebiAnimationIdle
	dw ZygardeAnimationIdle
	dw MewAnimationIdle
	dw MewtwoAnimationIdle
