FramesPointers:
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw ZoruaFrames
	dw ZoroarkFrames
	dw RockruffFrames
	dw LycanrocFrames
	dw MimikyuFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw MeowthFrames
	dw PersianFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw RotomFrames
	dw ChinglingFrames
	dw ChimechoFrames
	dw EspurrFrames
	dw Meowstic_MFrames
	dw TimburrFrames
	dw GurdurrFrames
	dw ConkeldurrFrames
	dw DittoFrames
	dw PurrloinFrames
	dw LiepardFrames
	dw VulpixFrames
	dw MukFrames
	dw Nidoran_MFrames
	dw NidorinoFrames
	dw NidorinaFrames
	dw NidokingFrames
	dw NidoqueenFrames
	dw SeviperFrames
	dw ZangooseFrames
	dw SentretFrames
	dw FurretFrames
	dw SwabluFrames
	dw AltariaFrames
	dw MienfooFrames
	dw MienshaoFrames
	dw HawluchaFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw ShinxFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw CutieflyFrames
	dw RibombeeFrames
	dw FlabebeFrames
	dw FloetteFrames
	dw FlorgesFrames
	dw IgglybuffFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ChespinFrames
	dw QuilladinFrames
	dw ChesnaughtFrames
	dw DeerlingFrames
	dw SawsbuckFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw FoongusFrames
	dw AmoongussFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw BonslyFrames
	dw SudowoodoFrames
	dw PassimianFrames
	dw StuffulFrames
	dw BewearFrames
	dw GirafarigFrames
	dw HeracrossFrames
	dw LedybaFrames
	dw LedianFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw PinecoFrames
	dw ForretressFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw ScytherFrames
	dw ScizorFrames
	dw VenipedeFrames
	dw WhirlipedeFrames
	dw ScolipedeFrames
	dw MorelullFrames
	dw ShiinoticFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw SandileFrames
	dw KrokorokFrames
	dw KrookodileFrames
	dw TympoleFrames
	dw PalpitoadFrames
	dw SeismitoadFrames
	dw DrampaFrames
	dw GoomyFrames
	dw SliggooFrames
	dw GoodraFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OshawottFrames
	dw DewottFrames
	dw SamurottFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw AzurillFrames
	dw MarillFrames
	dw AzumarillFrames
	dw LaprasFrames
	dw AnorithFrames
	dw ArmaldoFrames
	dw DewpiderFrames
	dw AraquanidFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw FeebasFrames
	dw MiloticFrames
	dw FinneonFrames
	dw LumineonFrames
	dw QwilfishFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw StunfiskFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw TyrogueFrames
	dw HitmonchanFrames
	dw HitmonleeFrames
	dw HitmontopFrames
	dw RioluFrames
	dw LucarioFrames
	dw MedititeFrames
	dw MedichamFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw FerroseedFrames
	dw FerrothornFrames
	dw ShuckleFrames
	dw NosepassFrames
	dw ProbopassFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw NoibatFrames
	dw NoivernFrames
	dw DruddigonFrames
	dw AxewFrames
	dw FraxureFrames
	dw HaxorusFrames
	dw Jangmo_oFrames
	dw Hakamo_oFrames
	dw Kommo_oFrames
	dw DeinoFrames
	dw ZweilousFrames
	dw HydreigonFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw LittenFrames
	dw TorracatFrames
	dw IncineroarFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw FletchlingFrames
	dw FletchinderFrames
	dw TalonflameFrames
	dw HeatmorFrames
	dw DurantFrames
	dw ArchenFrames
	dw UmbreonFrames
	dw RoggenrolaFrames
	dw BoldoreFrames
	dw GigalithFrames
	dw CarbinkFrames
	dw AmauraFrames
	dw AurorusFrames
	dw SneaselFrames
	dw WeavileFrames
	dw CryogonalFrames
	dw SnoruntFrames
	dw GlalieFrames
	dw FrosslassFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw UnownAFrames
	dw NatuFrames
	dw XatuFrames
	dw SigilyphFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw BaltoyFrames
	dw ClaydolFrames
	dw GolettFrames
	dw GolurkFrames
	dw BronzorFrames
	dw BronzongFrames
	dw HonedgeFrames
	dw DoubladeFrames
	dw AegislashFrames
	dw PawniardFrames
	dw BisharpFrames
	dw YamaskFrames
	dw CofagrigusFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw SpiritombFrames
	dw DuskullFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw SuicuneFrames
	dw RaikouFrames
	dw EnteiFrames
	dw LatiasFrames
	dw LatiosFrames
	dw SilvallyFrames
	dw MagearnaFrames
	dw ShayminFrames
	dw CelebiFrames
	dw ZygardeFrames
	dw MewFrames
	dw MewtwoFrames
