HoennBitmasksPointers::
	add_bitmasks Treecko
	add_bitmasks Grovyle
	add_bitmasks Sceptile
	add_bitmasks Torchic
	add_bitmasks Combusken
	add_bitmasks Blaziken
	add_bitmasks Mudkip
	add_bitmasks Marshtomp
	add_bitmasks Swampert
	add_bitmasks Poochyena
	add_bitmasks Mightyena
	add_bitmasks Zigzagoon
	add_bitmasks Linoone
	add_bitmasks Wurmple
	add_bitmasks Silcoon
	add_bitmasks Beautifly
	add_bitmasks Cascoon
	add_bitmasks Dustox
	add_bitmasks Lotad
	add_bitmasks Lombre
	add_bitmasks Ludicolo
	add_bitmasks Seedot
	add_bitmasks Nuzleaf
	add_bitmasks Shiftry
	add_bitmasks Taillow
	add_bitmasks Swellow
	add_bitmasks Wingull
	add_bitmasks Pelipper
	add_bitmasks Ralts
	add_bitmasks Kirlia
	add_bitmasks Gardevoir
	add_bitmasks Surskit
	add_bitmasks Masquerain
	add_bitmasks Shroomish
	add_bitmasks Breloom
	add_bitmasks Slakoth
	add_bitmasks Vigoroth
	add_bitmasks Slaking
	add_bitmasks Nincada
	add_bitmasks Ninjask
	add_bitmasks Shedinja
	add_bitmasks Whismur
	add_bitmasks Loudred
	add_bitmasks Exploud
	add_bitmasks Makuhita
	add_bitmasks Hariyama
	add_bitmasks Azurill
	add_bitmasks Nosepass
	add_bitmasks Skitty
	add_bitmasks Delcatty
	add_bitmasks Sableye
	add_bitmasks Mawile
	add_bitmasks Aron
	add_bitmasks Lairon
	add_bitmasks Aggron
	add_bitmasks Meditite
	add_bitmasks Medicham
	add_bitmasks Electrike
	add_bitmasks Manectric
	add_bitmasks Plusle
	add_bitmasks Minun
	add_bitmasks Volbeat
	add_bitmasks Illumise
	add_bitmasks Roselia
	add_bitmasks Gulpin
	add_bitmasks Swalot
	add_bitmasks Carvanha
	add_bitmasks Sharpedo
	add_bitmasks Wailmer
	add_bitmasks Wailord
	add_bitmasks Numel
	add_bitmasks Camerupt
	add_bitmasks Torkoal
	add_bitmasks Spoink
	add_bitmasks Grumpig
	add_bitmasks Spinda
	add_bitmasks Trapinch
	add_bitmasks Vibrava
	add_bitmasks Flygon
	add_bitmasks Cacnea
	add_bitmasks Cacturne
	add_bitmasks Swablu
	add_bitmasks Altaria
	add_bitmasks Zangoose
	add_bitmasks Seviper
	add_bitmasks Lunatone
	add_bitmasks Solrock
	add_bitmasks Barboach
	add_bitmasks Whiscash
	add_bitmasks Corphish
	add_bitmasks Crawdaunt
	add_bitmasks Baltoy
	add_bitmasks Claydol
	add_bitmasks Lileep
	add_bitmasks Cradily
	add_bitmasks Anorith
	add_bitmasks Armaldo
	add_bitmasks Feebas
	add_bitmasks Milotic
	add_bitmasks Castform
	add_bitmasks Kecleon
	add_bitmasks Shuppet
	add_bitmasks Banette
	add_bitmasks Duskull
	add_bitmasks Dusclops
	add_bitmasks Tropius
	add_bitmasks Chimecho
	add_bitmasks Absol
	add_bitmasks Snorunt
	add_bitmasks Glalie
	add_bitmasks Spheal
	add_bitmasks Sealeo
	add_bitmasks Walrein
	add_bitmasks Clamperl
	add_bitmasks Huntail
	add_bitmasks Gorebyss
	add_bitmasks Relicanth
	add_bitmasks Luvdisc
	add_bitmasks Bagon
	add_bitmasks Shelgon
	add_bitmasks Salamence
	add_bitmasks Beldum
	add_bitmasks Metang
	add_bitmasks Metagross
	add_bitmasks Regirock
	add_bitmasks Regice
	add_bitmasks Registeel
	add_bitmasks Latias
	add_bitmasks Latios
	add_bitmasks Kyogre
	add_bitmasks Groudon
	add_bitmasks Rayquaza
	add_bitmasks Jirachi
	add_bitmasks Deoxys
