HoennAnimationIdlePointers::
	add_idleanim Treecko
	add_idleanim Grovyle
	add_idleanim Sceptile
	add_idleanim Torchic
	add_idleanim Combusken
	add_idleanim Blaziken
	add_idleanim Mudkip
	add_idleanim Marshtomp
	add_idleanim Swampert
	add_idleanim Poochyena
	add_idleanim Mightyena
	add_idleanim Zigzagoon
	add_idleanim Linoone
	add_idleanim Wurmple
	add_idleanim Silcoon
	add_idleanim Beautifly
	add_idleanim Cascoon
	add_idleanim Dustox
	add_idleanim Lotad
	add_idleanim Lombre
	add_idleanim Ludicolo
	add_idleanim Seedot
	add_idleanim Nuzleaf
	add_idleanim Shiftry
	add_idleanim Taillow
	add_idleanim Swellow
	add_idleanim Wingull
	add_idleanim Pelipper
	add_idleanim Ralts
	add_idleanim Kirlia
	add_idleanim Gardevoir
	add_idleanim Gallade
	add_idleanim Surskit
	add_idleanim Masquerain
	add_idleanim Shroomish
	add_idleanim Breloom
	add_idleanim Slakoth
	add_idleanim Vigoroth
	add_idleanim Slaking
	add_idleanim Nincada
	add_idleanim Ninjask
	add_idleanim Shedinja 
 	add_idleanim Whismur
	add_idleanim Loudred
	add_idleanim Exploud
	add_idleanim Makuhita
	add_idleanim Hariyama
	add_idleanim Nosepass
	add_idleanim Probopass
	add_idleanim Skitty
	add_idleanim Delcatty
	add_idleanim Sableye
	add_idleanim Mawile
	add_idleanim Aron 
 	add_idleanim Lairon
	add_idleanim Aggron
	add_idleanim Meditite
	add_idleanim Medicham
	add_idleanim Electrike
	add_idleanim Manectric
	add_idleanim Plusle
	add_idleanim Minun
	add_idleanim Volbeat
	add_idleanim Illumise
	add_idleanim Budew
	add_idleanim Roselia
	add_idleanim Roserade
	add_idleanim Gulpin
	add_idleanim Swalot
	add_idleanim Carvanha
	add_idleanim Sharpedo
	add_idleanim Wailmer
	add_idleanim Wailord
	add_idleanim Numel
	add_idleanim Camerupt
	add_idleanim Torkoal
	add_idleanim Spoink
	add_idleanim Grumpig
	add_idleanim Spinda
	add_idleanim Trapinch
	add_idleanim Vibrava
	add_idleanim Flygon
	add_idleanim Cacnea
	add_idleanim Cacturne 
 	add_idleanim Swablu
	add_idleanim Altaria
	add_idleanim Zangoose
	add_idleanim Seviper
	add_idleanim Lunatone
	add_idleanim Solrock
	add_idleanim Barboach
	add_idleanim Whiscash
	add_idleanim Corphish
	add_idleanim Crawdaunt
	add_idleanim Baltoy
	add_idleanim Claydol
	add_idleanim Lileep
	add_idleanim Cradily
	add_idleanim Anorith
	add_idleanim Armaldo
	add_idleanim Feebas
	add_idleanim Milotic
	add_idleanim Castform 
	add_idleanim Kecleon
	add_idleanim Shuppet
	add_idleanim Banette
	add_idleanim Duskull
	add_idleanim Dusclops
	add_idleanim Dusknoir
	add_idleanim Tropius
	add_idleanim Chingling
	add_idleanim Chimecho
	add_idleanim Absol
	add_idleanim Snorunt
	add_idleanim Glalie
	add_idleanim Frosslass
	add_idleanim Spheal
	add_idleanim Sealeo
	add_idleanim Walrein
	add_idleanim Clamperl
	add_idleanim Huntail
	add_idleanim Gorebyss
	add_idleanim Relicanth
	add_idleanim Luvdisc
	add_idleanim Bagon
	add_idleanim Shelgon
	add_idleanim Salamence
	add_idleanim Beldum
	add_idleanim Metang
	add_idleanim Metagross
	add_idleanim Regirock
	add_idleanim Regice
	add_idleanim Registeel
	add_idleanim Latias
	add_idleanim Latios
	add_idleanim Kyogre 
 	add_idleanim Groudon
	add_idleanim Rayquaza
	add_idleanim Jirachi
	add_idleanim Deoxys_Defense
	add_idleanim Deoxys_Normal
	add_idleanim Deoxys_Attack
	add_idleanim Deoxys_Speed