HoennFramesPointers::
	add_frames Treecko
	add_frames Grovyle
	add_frames Sceptile
	add_frames Torchic
	add_frames Combusken
	add_frames Blaziken
	add_frames Mudkip
	add_frames Marshtomp
	add_frames Swampert
	add_frames Poochyena
	add_frames Mightyena
	add_frames Zigzagoon
	add_frames Linoone
	add_frames Wurmple
	add_frames Silcoon
	add_frames Beautifly
	add_frames Cascoon
	add_frames Dustox
	add_frames Lotad
	add_frames Lombre
	add_frames Ludicolo
	add_frames Seedot
	add_frames Nuzleaf
	add_frames Shiftry
	add_frames Taillow
	add_frames Swellow
	add_frames Wingull
	add_frames Pelipper
	add_frames Ralts
	add_frames Kirlia
	add_frames Gardevoir
	add_frames Surskit
	add_frames Masquerain
	add_frames Shroomish
	add_frames Breloom
	add_frames Slakoth
	add_frames Vigoroth
	add_frames Slaking
	add_frames Nincada
	add_frames Ninjask
	add_frames Shedinja
	add_frames Whismur
	add_frames Loudred
	add_frames Exploud
	add_frames Makuhita
	add_frames Hariyama
	add_frames Azurill
	add_frames Nosepass
	add_frames Skitty
	add_frames Delcatty
	add_frames Sableye
	add_frames Mawile
	add_frames Aron
	add_frames Lairon
	add_frames Aggron
	add_frames Meditite
	add_frames Medicham
	add_frames Electrike
	add_frames Manectric
	add_frames Plusle
	add_frames Minun
	add_frames Volbeat
	add_frames Illumise
	add_frames Roselia
	add_frames Gulpin
	add_frames Swalot
	add_frames Carvanha
	add_frames Sharpedo
	add_frames Wailmer
	add_frames Wailord
	add_frames Numel
	add_frames Camerupt
	add_frames Torkoal
	add_frames Spoink
	add_frames Grumpig
	add_frames Spinda
	add_frames Trapinch
	add_frames Vibrava
	add_frames Flygon
	add_frames Cacnea
	add_frames Cacturne
	add_frames Swablu
	add_frames Altaria
	add_frames Zangoose
	add_frames Seviper
	add_frames Lunatone
	add_frames Solrock
	add_frames Barboach
	add_frames Whiscash
	add_frames Corphish
	add_frames Crawdaunt
	add_frames Baltoy
	add_frames Claydol
	add_frames Lileep
	add_frames Cradily
	add_frames Anorith
	add_frames Armaldo
	add_frames Feebas
	add_frames Milotic
	add_frames Castform
	add_frames Kecleon
	add_frames Shuppet
	add_frames Banette
	add_frames Duskull
	add_frames Dusclops
	add_frames Tropius
	add_frames Chimecho
	add_frames Absol
	add_frames Snorunt
	add_frames Glalie
	add_frames Spheal
	add_frames Sealeo
	add_frames Walrein
	add_frames Clamperl
	add_frames Huntail
	add_frames Gorebyss
	add_frames Relicanth
	add_frames Luvdisc
	add_frames Bagon
	add_frames Shelgon
	add_frames Salamence
	add_frames Beldum
	add_frames Metang
	add_frames Metagross
	add_frames Regirock
	add_frames Regice
	add_frames Registeel
	add_frames Latias
	add_frames Latios
	add_frames Kyogre
	add_frames Groudon
	add_frames Rayquaza
	add_frames Jirachi
	add_frames Deoxys
