HoennAnimationPointers::
	add_anim Treecko
	add_anim Grovyle
	add_anim Sceptile
	add_anim Torchic
	add_anim Combusken
	add_anim Blaziken
	add_anim Mudkip
	add_anim Marshtomp
	add_anim Swampert
	add_anim Poochyena
	add_anim Mightyena
	add_anim Zigzagoon
	add_anim Linoone
	add_anim Wurmple
	add_anim Silcoon
	add_anim Beautifly
	add_anim Cascoon
	add_anim Dustox
	add_anim Lotad
	add_anim Lombre
	add_anim Ludicolo
	add_anim Seedot
	add_anim Nuzleaf
	add_anim Shiftry
	add_anim Taillow
	add_anim Swellow
	add_anim Wingull
	add_anim Pelipper
	add_anim Ralts
	add_anim Kirlia
	add_anim Gardevoir
	add_anim Surskit
	add_anim Masquerain
	add_anim Shroomish
	add_anim Breloom
	add_anim Slakoth
	add_anim Vigoroth
	add_anim Slaking
	add_anim Nincada
	add_anim Ninjask
	add_anim Shedinja
	add_anim Whismur
	add_anim Loudred
	add_anim Exploud
	add_anim Makuhita
	add_anim Hariyama
	add_anim Azurill
	add_anim Nosepass
	add_anim Skitty
	add_anim Delcatty
	add_anim Sableye
	add_anim Mawile
	add_anim Aron
	add_anim Lairon
	add_anim Aggron
	add_anim Meditite
	add_anim Medicham
	add_anim Electrike
	add_anim Manectric
	add_anim Plusle
	add_anim Minun
	add_anim Volbeat
	add_anim Illumise
	add_anim Roselia
	add_anim Gulpin
	add_anim Swalot
	add_anim Carvanha
	add_anim Sharpedo
	add_anim Wailmer
	add_anim Wailord
	add_anim Numel
	add_anim Camerupt
	add_anim Torkoal
	add_anim Spoink
	add_anim Grumpig
	add_anim Spinda
	add_anim Trapinch
	add_anim Vibrava
	add_anim Flygon
	add_anim Cacnea
	add_anim Cacturne
	add_anim Swablu
	add_anim Altaria
	add_anim Zangoose
	add_anim Seviper
	add_anim Lunatone
	add_anim Solrock
	add_anim Barboach
	add_anim Whiscash
	add_anim Corphish
	add_anim Crawdaunt
	add_anim Baltoy
	add_anim Claydol
	add_anim Lileep
	add_anim Cradily
	add_anim Anorith
	add_anim Armaldo
	add_anim Feebas
	add_anim Milotic
	add_anim Castform
	add_anim Kecleon
	add_anim Shuppet
	add_anim Banette
	add_anim Duskull
	add_anim Dusclops
	add_anim Tropius
	add_anim Chimecho
	add_anim Absol
	add_anim Wynaut
	add_anim Snorunt
	add_anim Glalie
	add_anim Spheal
	add_anim Sealeo
	add_anim Walrein
	add_anim Clamperl
	add_anim Huntail
	add_anim Gorebyss
	add_anim Relicanth
	add_anim Luvdisc
	add_anim Bagon
	add_anim Shelgon
	add_anim Salamence
	add_anim Beldum
	add_anim Metang
	add_anim Metagross
	add_anim Regirock
	add_anim Regice
	add_anim Registeel
	add_anim Latias
	add_anim Latios
	add_anim Kyogre
	add_anim Groudon
	add_anim Rayquaza
	add_anim Jirachi
	add_anim Deoxys
