JohtoFramesPointers::
	add_frames Chikorita
	add_frames Bayleef
	add_frames Meganium
	add_frames Cyndaquil
	add_frames Quilava
	add_frames Typhlosion
	add_frames Totodile
	add_frames Croconaw
	add_frames Feraligatr
	add_frames Sentret
	add_frames Furret
	add_frames Hoothoot
	add_frames Noctowl
	add_frames Ledyba
	add_frames Ledian
	add_frames Spinarak
	add_frames Ariados
	add_frames Crobat
	add_frames Chinchou
	add_frames Lanturn
	add_frames Pichu
	add_frames Cleffa
	add_frames Igglybuff
	add_frames Togepi
	add_frames Togetic
	add_frames Natu
	add_frames Xatu
	add_frames Mareep
	add_frames Flaaffy
	add_frames Ampharos
	add_frames Bellossom
	add_frames Marill
	add_frames Azumarill
	add_frames Sudowoodo
	add_frames Politoed
	add_frames Hoppip
	add_frames Skiploom
	add_frames Jumpluff
	add_frames Aipom
	add_frames Sunkern
	add_frames Sunflora
	add_frames Yanma
	add_frames Wooper
	add_frames Quagsire
	add_frames Espeon
	add_frames Umbreon
	add_frames Murkrow
	add_frames Slowking
	add_frames Misdreavus
	add_frames Unown
	add_frames Wobbuffet
	add_frames Girafarig
	add_frames Pineco
	add_frames Forretress
	add_frames Dunsparce
	add_frames Gligar
	add_frames Steelix
	add_frames Snubbull
	add_frames Granbull
	add_frames Qwilfish
	add_frames Scizor
	add_frames Shuckle
	add_frames Heracross
	add_frames Sneasel
	add_frames Teddiursa
	add_frames Ursaring
	add_frames Slugma
	add_frames Magcargo
	add_frames Swinub
	add_frames Piloswine
	add_frames Corsola
	add_frames Remoraid
	add_frames Octillery
	add_frames Delibird
	add_frames Mantine
	add_frames Skarmory
	add_frames Houndour
	add_frames Houndoom
	add_frames Kingdra
	add_frames Phanpy
	add_frames Donphan
	add_frames Porygon2
	add_frames Stantler
	add_frames Smeargle
	add_frames Tyrogue
	add_frames Hitmontop
	add_frames Smoochum
	add_frames Elekid
	add_frames Magby
	add_frames Miltank
	add_frames Blissey
	add_frames Raikou
	add_frames Entei
	add_frames Suicune
	add_frames Larvitar
	add_frames Pupitar
	add_frames Tyranitar
	add_frames Lugia
	add_frames Ho_Oh
	add_frames Celebi
