JohtoAnimationPointers::
	add_anim Chikorita
	add_anim Bayleef
	add_anim Meganium
	add_anim Cyndaquil
	add_anim Quilava
	add_anim Typhlosion
	add_anim Totodile
	add_anim Croconaw
	add_anim Feraligatr
	add_anim Sentret
	add_anim Furret
	add_anim Hoothoot
	add_anim Noctowl
	add_anim Ledyba
	add_anim Ledian
	add_anim Spinarak
	add_anim Ariados
	add_anim Crobat
	add_anim Chinchou
	add_anim Lanturn
	add_anim Pichu
	add_anim Cleffa
	add_anim Igglybuff
	add_anim Togepi
	add_anim Togetic
	add_anim Natu
	add_anim Xatu
	add_anim Mareep
	add_anim Flaaffy
	add_anim Ampharos
	add_anim Bellossom
	add_anim Marill
	add_anim Azumarill
	add_anim Sudowoodo
	add_anim Politoed
	add_anim Hoppip
	add_anim Skiploom
	add_anim Jumpluff
	add_anim Aipom
	add_anim Sunkern
	add_anim Sunflora
	add_anim Yanma
	add_anim Wooper
	add_anim Quagsire
	add_anim Espeon
	add_anim Umbreon
	add_anim Murkrow
	add_anim Slowking
	add_anim Misdreavus
	add_anim Unown
	add_anim Wobbuffet
	add_anim Girafarig
	add_anim Pineco
	add_anim Forretress
	add_anim Dunsparce
	add_anim Gligar
	add_anim Steelix
	add_anim Snubbull
	add_anim Granbull
	add_anim Qwilfish
	add_anim Scizor
	add_anim Shuckle
	add_anim Heracross
	add_anim Sneasel
	add_anim Teddiursa
	add_anim Ursaring
	add_anim Slugma
	add_anim Magcargo
	add_anim Swinub
	add_anim Piloswine
	add_anim Corsola
	add_anim Remoraid
	add_anim Octillery
	add_anim Delibird
	add_anim Mantine
	add_anim Skarmory
	add_anim Houndour
	add_anim Houndoom
	add_anim Kingdra
	add_anim Phanpy
	add_anim Donphan
	add_anim Porygon2
	add_anim Stantler
	add_anim Smeargle
	add_anim Tyrogue
	add_anim Hitmontop
	add_anim Smoochum
	add_anim Elekid
	add_anim Magby
	add_anim Miltank
	add_anim Blissey
	add_anim Raikou
	add_anim Entei
	add_anim Suicune
	add_anim Larvitar
	add_anim Pupitar
	add_anim Tyranitar
	add_anim Lugia
	add_anim Ho_Oh
	add_anim Celebi
