JohtoBitmasksPointers::
	add_bitmasks Chikorita
	add_bitmasks Bayleef
	add_bitmasks Meganium
	add_bitmasks Cyndaquil
	add_bitmasks Quilava
	add_bitmasks Typhlosion
	add_bitmasks Totodile
	add_bitmasks Croconaw
	add_bitmasks Feraligatr
	add_bitmasks Sentret
	add_bitmasks Furret
	add_bitmasks Hoothoot
	add_bitmasks Noctowl
	add_bitmasks Ledyba
	add_bitmasks Ledian
	add_bitmasks Spinarak
	add_bitmasks Ariados
	add_bitmasks Chinchou
	add_bitmasks Lanturn
	add_bitmasks Togepi
	add_bitmasks Togetic
	add_bitmasks Togekiss
	add_bitmasks Natu
	add_bitmasks Xatu
	add_bitmasks Mareep
	add_bitmasks Flaaffy
	add_bitmasks Ampharos
	add_bitmasks Azurill
	add_bitmasks Marill
	add_bitmasks Azumarill
	add_bitmasks Bonsly
	add_bitmasks Sudowoodo
	add_bitmasks Hoppip
	add_bitmasks Skiploom
	add_bitmasks Jumpluff
	add_bitmasks Aipom
    add_bitmasks Ambipom
	add_bitmasks Sunkern
	add_bitmasks Sunflora
	add_bitmasks Yanma
	add_bitmasks Yanmega
	add_bitmasks Wooper
	add_bitmasks Quagsire
	add_bitmasks Murkrow
	add_bitmasks Honchkrow
	add_bitmasks Misdreavus
	add_bitmasks Mismagius
	add_bitmasks Unown
    add_bitmasks Wynaut
	add_bitmasks Wobbuffet
	add_bitmasks Girafarig
	add_bitmasks Pineco
	add_bitmasks Forretress
	add_bitmasks Dunsparce
	add_bitmasks Gligar
	add_bitmasks Gliscor
	add_bitmasks Snubbull
	add_bitmasks Granbull
	add_bitmasks Qwilfish
	add_bitmasks Shuckle
	add_bitmasks Heracross
	add_bitmasks Sneasel
	add_bitmasks Weavile
	add_bitmasks Teddiursa
	add_bitmasks Ursaring
	add_bitmasks Slugma
	add_bitmasks Magcargo
	add_bitmasks Swinub
	add_bitmasks Piloswine
	add_bitmasks Mamoswine
	add_bitmasks Corsola
	add_bitmasks Remoraid
	add_bitmasks Octillery
	add_bitmasks Delibird
	add_bitmasks Mantyke
	add_bitmasks Mantine
	add_bitmasks Skarmory
	add_bitmasks Houndour
	add_bitmasks Houndoom
	add_bitmasks Phanpy
	add_bitmasks Donphan
	add_bitmasks Stantler
	add_bitmasks Smeargle
	add_bitmasks Miltank
	add_bitmasks Raikou
	add_bitmasks Entei
	add_bitmasks Suicune
	add_bitmasks Larvitar
	add_bitmasks Pupitar
	add_bitmasks Tyranitar
	add_bitmasks Lugia
	add_bitmasks HoOh
	add_bitmasks Celebi