JohtoFramesPointers::
	add_frames Chikorita
	add_frames Bayleef
	add_frames Meganium
	add_frames Cyndaquil
	add_frames Quilava
	add_frames Typhlosion
	add_frames Totodile
	add_frames Croconaw
	add_frames Feraligatr
	add_frames Sentret
	add_frames Furret
	add_frames Hoothoot
	add_frames Noctowl
	add_frames Ledyba
	add_frames Ledian
	add_frames Spinarak
	add_frames Ariados
	add_frames Chinchou
	add_frames Lanturn
	add_frames Togepi
	add_frames Togetic
	add_frames Togekiss
	add_frames Natu
	add_frames Xatu
	add_frames Mareep
	add_frames Flaaffy
	add_frames Ampharos
	add_frames Azurill
	add_frames Marill
	add_frames Azumarill
	add_frames Bonsly
	add_frames Sudowoodo
	add_frames Hoppip
	add_frames Skiploom
	add_frames Jumpluff
	add_frames Aipom
    add_frames Ambipom
	add_frames Sunkern
	add_frames Sunflora
	add_frames Yanma
	add_frames Yanmega
	add_frames Wooper
	add_frames Quagsire
	add_frames Murkrow
	add_frames Honchkrow
	add_frames Misdreavus
	add_frames Mismagius
	add_frames Unown
    add_frames Wynaut
	add_frames Wobbuffet
	add_frames Girafarig
	add_frames Pineco
	add_frames Forretress
	add_frames Dunsparce
	add_frames Gligar
	add_frames Gliscor
	add_frames Snubbull
	add_frames Granbull
	add_frames Qwilfish
	add_frames Shuckle
	add_frames Heracross
	add_frames Sneasel
	add_frames Weavile
	add_frames Teddiursa
	add_frames Ursaring
	add_frames Slugma
	add_frames Magcargo
	add_frames Swinub
	add_frames Piloswine
	add_frames Mamoswine
	add_frames Corsola
	add_frames Remoraid
	add_frames Octillery
	add_frames Delibird
	add_frames Mantyke
	add_frames Mantine
	add_frames Skarmory
	add_frames Houndour
	add_frames Houndoom
	add_frames Phanpy
	add_frames Donphan
	add_frames Stantler
	add_frames Smeargle
	add_frames Miltank
	add_frames Raikou
	add_frames Entei
	add_frames Suicune
	add_frames Larvitar
	add_frames Pupitar
	add_frames Tyranitar
	add_frames Lugia
	add_frames HoOh
	add_frames Celebi