KalosBitmasksPointers::
	add_bitmasks Chespin
	add_bitmasks Quilladin
	add_bitmasks Chesnaught
	add_bitmasks Fennekin
	add_bitmasks Braixen
	add_bitmasks Delphox
	add_bitmasks Froakie
	add_bitmasks Frogadier
	add_bitmasks Greninja
	add_bitmasks Bunnelby
	add_bitmasks Diggersby
	add_bitmasks Fletchling
	add_bitmasks Fletchinder
	add_bitmasks Talonflame
	add_bitmasks Scatterbug
	add_bitmasks Spewpa
	add_bitmasks Vivvilon
	add_bitmasks Litleo
	add_bitmasks Pyroar
	add_bitmasks Flabebe
	add_bitmasks Floette
	add_bitmasks Florges
	add_bitmasks Skiddo
	add_bitmasks Gogoat
	add_bitmasks Pancham
	add_bitmasks Pangoro
	add_bitmasks Furfrou
	add_bitmasks Espurr
	add_bitmasks Meowstic
	add_bitmasks Honedge
	add_bitmasks Doublade
	add_bitmasks Aegislash
	add_bitmasks Spritzee
	add_bitmasks Aromatisse
	add_bitmasks Swirlix
	add_bitmasks Slurpuff
	add_bitmasks Inkay
	add_bitmasks Malamar
	add_bitmasks Binacle
	add_bitmasks Barbracle
	add_bitmasks Skrelp
	add_bitmasks Dragalge
	add_bitmasks Clauncher
	add_bitmasks Clawlitzer
	add_bitmasks Helioptile
	add_bitmasks Heliolisk
	add_bitmasks Tyrunt
	add_bitmasks Tyrantrum
	add_bitmasks Amaura
	add_bitmasks Aurorus
	add_bitmasks Sylveon
	add_bitmasks Hawlucha
	add_bitmasks Dedenne
	add_bitmasks Carbink
	add_bitmasks Goomy
	add_bitmasks Sliggoo
	add_bitmasks Goodra
	add_bitmasks Klefki
	add_bitmasks Phantump
	add_bitmasks Trevenant
	add_bitmasks Pumpkaboo
	add_bitmasks Gourgeist
	add_bitmasks Bergmite
	add_bitmasks Avalugg
	add_bitmasks Noibat
	add_bitmasks Noivern
	add_bitmasks Xerneas
	add_bitmasks Yveltal
	add_bitmasks Zygarde
	add_bitmasks Diancie
	add_bitmasks Hoopa
	add_bitmasks Volcanion
