KalosAnimationPointers::
	add_anim Chespin
	add_anim Quilladin
	add_anim Chesnaught
	add_anim Fennekin
	add_anim Braixen
	add_anim Delphox
	add_anim Froakie
	add_anim Frogadier
	add_anim Greninja
	add_anim Bunnelby
	add_anim Diggersby
	add_anim Fletchling
	add_anim Fletchinder
	add_anim Talonflame
	add_anim Scatterbug
	add_anim Spewpa
	add_anim Vivillon
	add_anim Litleo
	add_anim Pyroar
	add_anim Flabebe
	add_anim Floette
	add_anim Florges
	add_anim Skiddo
	add_anim Gogoat
	add_anim Pancham
	add_anim Pangoro
	add_anim Furfrou
	add_anim Espurr
	add_anim Meowstic
	add_anim Honedge
	add_anim Doublade
	add_anim Aegislash
	add_anim Spritzee
	add_anim Aromatisse
	add_anim Swirlix
	add_anim Slurpuff
	add_anim Inkay
	add_anim Malamar
	add_anim Binacle
	add_anim Barbaracle
	add_anim Skrelp
	add_anim Dragalge
	add_anim Clauncher
	add_anim Clawitzer
	add_anim Helioptile
	add_anim Heliolisk
	add_anim Tyrunt
	add_anim Tyrantrum
	add_anim Amaura
	add_anim Aurorus
	add_anim Sylveon
	add_anim Hawlucha
	add_anim Dedenne
	add_anim Carbink
	add_anim Goomy
	add_anim Sliggoo
	add_anim Goodra
	add_anim Klefki
	add_anim Phantump
	add_anim Trevenant
	add_anim Pumpkaboo
	add_anim Gourgeist
	add_anim Bergmite
	add_anim Avalugg
	add_anim Noibat
	add_anim Noivern
	add_anim Xerneas
	add_anim Yveltal
	add_anim Zygarde
	add_anim Diancie
	add_anim Hoopa
	add_anim Volcanion
