KalosFramesPointers::
	add_frames Chespin
	add_frames Quilladin
	add_frames Chesnaught
	add_frames Fennekin
	add_frames Braixen
	add_frames Delphox
	add_frames Froakie
	add_frames Frogadier
	add_frames Greninja
	add_frames Bunnelby
	add_frames Diggersby
	add_frames Fletchling
	add_frames Fletchinder
	add_frames Talonflame
	add_frames Scatterbug
	add_frames Spewpa
	add_frames Vivvilon
	add_frames Litleo
	add_frames Pyroar
	add_frames Flabebe
	add_frames Floette
	add_frames Florges
	add_frames Skiddo
	add_frames Gogoat
	add_frames Pancham
	add_frames Pangoro
	add_frames Furfrou
	add_frames Espurr
	add_frames Meowstic
	add_frames Honedge
	add_frames Doublade
	add_frames Aegislash
	add_frames Spritzee
	add_frames Aromatisse
	add_frames Swirlix
	add_frames Slurpuff
	add_frames Inkay
	add_frames Malamar
	add_frames Binacle
	add_frames Barbracle
	add_frames Skrelp
	add_frames Dragalge
	add_frames Clauncher
	add_frames Clawlitzer
	add_frames Helioptile
	add_frames Heliolisk
	add_frames Tyrunt
	add_frames Tyrantrum
	add_frames Amaura
	add_frames Aurorus
	add_frames Sylveon
	add_frames Hawlucha
	add_frames Dedenne
	add_frames Carbink
	add_frames Goomy
	add_frames Sliggoo
	add_frames Goodra
	add_frames Klefki
	add_frames Phantump
	add_frames Trevenant
	add_frames Pumpkaboo
	add_frames Gourgeist
	add_frames Bergmite
	add_frames Avalugg
	add_frames Noibat
	add_frames Noivern
	add_frames Xerneas
	add_frames Yveltal
	add_frames Zygarde
	add_frames Diancie
	add_frames Hoopa
	add_frames Volcanion
