KalosAnimationIdlePointers::
	add_idleanim Chespin
	add_idleanim Quilladin
	add_idleanim Chesnaught
	add_idleanim Fennekin
	add_idleanim Braixen
	add_idleanim Delphox
	add_idleanim Froakie
	add_idleanim Frogadier
	add_idleanim Greninja
	add_idleanim Bunnelby
	add_idleanim Diggersby
	add_idleanim Fletchling
	add_idleanim Fletchinder
	add_idleanim Talonflame
	add_idleanim Scatterbug
	add_idleanim Spewpa
	add_idleanim Vivvilon
	add_idleanim Litleo
	add_idleanim Pyroar
	add_idleanim Flabebe
	add_idleanim Floette
	add_idleanim Florges
	add_idleanim Skiddo
	add_idleanim Gogoat
	add_idleanim Pancham
	add_idleanim Pangoro
	add_idleanim Furfrou
	add_idleanim Espurr
	add_idleanim Meowstic
	add_idleanim Honedge
	add_idleanim Doublade
	add_idleanim Aegislash
	add_idleanim Spritzee
	add_idleanim Aromatisse
	add_idleanim Swirlix
	add_idleanim Slurpuff
	add_idleanim Inkay
	add_idleanim Malamar
	add_idleanim Binacle
	add_idleanim Barbracle
	add_idleanim Skrelp
	add_idleanim Dragalge
	add_idleanim Clauncher
	add_idleanim Clawlitzer
	add_idleanim Helioptile
	add_idleanim Heliolisk
	add_idleanim Tyrunt
	add_idleanim Tyrantrum
	add_idleanim Amaura
	add_idleanim Aurorus
	add_idleanim Sylveon
	add_idleanim Hawlucha
	add_idleanim Dedenne
	add_idleanim Carbink
	add_idleanim Goomy
	add_idleanim Sliggoo
	add_idleanim Goodra
	add_idleanim Klefki
	add_idleanim Phantump
	add_idleanim Trevenant
	add_idleanim Pumpkaboo
	add_idleanim Gourgeist
	add_idleanim Bergmite
	add_idleanim Avalugg
	add_idleanim Noibat
	add_idleanim Noivern
	add_idleanim Xerneas
	add_idleanim Yveltal
	add_idleanim Zygarde
	add_idleanim Diancie
	add_idleanim Hoopa
	add_idleanim Volcanion
