KantoBitmasksPointers::
    add_bitmasks Bulbasaur
    add_bitmasks Ivysaur
    add_bitmasks Venusaur
    add_bitmasks Charmander
    add_bitmasks Charmeleon
    add_bitmasks Charizard
    add_bitmasks Squirtle
    add_bitmasks Wartortle
    add_bitmasks Blastoise
    add_bitmasks Caterpie
    add_bitmasks Metapod
    add_bitmasks Butterfree
    add_bitmasks Weedle
    add_bitmasks Kakuna
    add_bitmasks Beedrill
    add_bitmasks Pidgey
    add_bitmasks Pidgeotto
    add_bitmasks Pidgeot
    add_bitmasks Rattata
    add_bitmasks Raticate
    add_bitmasks Spearow
    add_bitmasks Fearow
    add_bitmasks Ekans
    add_bitmasks Arbok
    add_bitmasks Pichu
    add_bitmasks Pikachu
    add_bitmasks Raichu
    add_bitmasks Sandshrew
    add_bitmasks Sandslash
    add_bitmasks Nidoran_F
    add_bitmasks Nidorina
    add_bitmasks Nidoqueen
    add_bitmasks Nidoran_M
    add_bitmasks Nidorino
    add_bitmasks Nidoking
    add_bitmasks Cleffa
    add_bitmasks Clefairy
    add_bitmasks Clefable
    add_bitmasks Vulpix
    add_bitmasks Ninetales
    add_bitmasks Igglybuff
    add_bitmasks Jigglypuff
    add_bitmasks Wigglytuff
    add_bitmasks Zubat
    add_bitmasks Golbat
    add_bitmasks Crobat
    add_bitmasks Oddish
    add_bitmasks Gloom
    add_bitmasks Vileplume
    add_bitmasks Bellossom
    add_bitmasks Paras
    add_bitmasks Parasect
    add_bitmasks Venonat
    add_bitmasks Venomoth
    add_bitmasks Diglett
    add_bitmasks Dugtrio
    add_bitmasks Meowth
    add_bitmasks Persian
    add_bitmasks Psyduck
    add_bitmasks Golduck
    add_bitmasks Mankey
    add_bitmasks Primeape
    add_bitmasks Growlithe
    add_bitmasks Arcanine
    add_bitmasks Poliwag
    add_bitmasks Poliwhirl
    add_bitmasks Poliwrath
    add_bitmasks Politoed
    add_bitmasks Abra
    add_bitmasks Kadabra
    add_bitmasks Alakazam
    add_bitmasks Machop
    add_bitmasks Machoke
    add_bitmasks Machamp
    add_bitmasks Bellsprout
    add_bitmasks Weepinbell
    add_bitmasks Victreebel
    add_bitmasks Tentacool
    add_bitmasks Tentacruel
    add_bitmasks Geodude
    add_bitmasks Graveler
    add_bitmasks Golem
    add_bitmasks Ponyta
    add_bitmasks Rapidash
    add_bitmasks Slowpoke
    add_bitmasks Slowbro
    add_bitmasks Slowking
    add_bitmasks Magnemite
    add_bitmasks Magneton
    add_bitmasks Magnezone
    add_bitmasks FarfetchD
    add_bitmasks Doduo
    add_bitmasks Dodrio
    add_bitmasks Seel
    add_bitmasks Dewgong
    add_bitmasks Grimer
    add_bitmasks Muk
    add_bitmasks Shellder
    add_bitmasks Cloyster
    add_bitmasks Gastly
    add_bitmasks Haunter
    add_bitmasks Gengar
    add_bitmasks Onix
    add_bitmasks Steelix
    add_bitmasks Drowzee
    add_bitmasks Hypno
    add_bitmasks Krabby
    add_bitmasks Kingler
    add_bitmasks Voltorb
    add_bitmasks Electrode
    add_bitmasks Exeggcute
    add_bitmasks Exeggutor
    add_bitmasks Cubone
    add_bitmasks Marowak
    add_bitmasks Tyrogue
    add_bitmasks Hitmonlee
    add_bitmasks Hitmonchan
    add_bitmasks Hitmontop
    add_bitmasks Lickitung
    add_bitmasks Lickilicky
    add_bitmasks Koffing
    add_bitmasks Weezing
    add_bitmasks Rhyhorn
    add_bitmasks Rhydon
    add_bitmasks Rhyperior
    add_bitmasks Happiny
    add_bitmasks Chansey
    add_bitmasks Blissey
    add_bitmasks Tangela
    add_bitmasks Tangrowth
    add_bitmasks Kangaskhan
    add_bitmasks Horsea
    add_bitmasks Seadra
    add_bitmasks Kingdra
    add_bitmasks Goldeen
    add_bitmasks Seaking
    add_bitmasks Staryu
    add_bitmasks Starmie
    add_bitmasks Mime_Jr
    add_bitmasks MrMime
    add_bitmasks Scyther
    add_bitmasks Scizor
    add_bitmasks Smoochum
    add_bitmasks Jynx
    add_bitmasks Elekid
    add_bitmasks Electabuzz
    add_bitmasks Electivire
    add_bitmasks Magby
    add_bitmasks Magmar
    add_bitmasks Magmortar
    add_bitmasks Pinsir
    add_bitmasks Tauros
    add_bitmasks Magikarp
    add_bitmasks Gyarados
    add_bitmasks Lapras
    add_bitmasks Ditto
    add_bitmasks Eevee
    add_bitmasks Vaporeon
    add_bitmasks Jolteon
    add_bitmasks Flareon
    add_bitmasks Espeon
    add_bitmasks Umbreon
    add_bitmasks Leafeon
    add_bitmasks Glaceon
    add_bitmasks Sylveon
    add_bitmasks Porygon
    add_bitmasks Porygon2
    add_bitmasks PorygonZ
    add_bitmasks Omanyte
    add_bitmasks Omastar
    add_bitmasks Kabuto
    add_bitmasks Kabutops
    add_bitmasks Aerodactyl
    add_bitmasks Munchlax
    add_bitmasks Snorlax
    add_bitmasks Articuno
    add_bitmasks Zapdos
    add_bitmasks Moltres
    add_bitmasks Dratini
    add_bitmasks Dragonair
    add_bitmasks Dragonite
    add_bitmasks Mewtwo
    add_bitmasks Mew
    add_bitmasks Madaamu