KantoAnimationPointers::
    add_anim Bulbasaur
    add_anim Ivysaur
    add_anim Venusaur
    add_anim Charmander
    add_anim Charmeleon
    add_anim Charizard
    add_anim Squirtle
    add_anim Wartortle
    add_anim Blastoise
    add_anim Caterpie
    add_anim Metapod
    add_anim Butterfree
    add_anim Weedle
    add_anim Kakuna
    add_anim Beedrill
    add_anim Pidgey
    add_anim Pidgeotto
    add_anim Pidgeot
    add_anim Rattata
    add_anim Raticate
    add_anim Rattata_Alola
    add_anim Raticate_Alola
    add_anim Spearow
    add_anim Fearow
    add_anim Ekans
    add_anim Arbok
    add_anim Pichu
    add_anim Pikachu
    add_anim Raichu
    add_anim Raichu_Alola
    add_anim Sandshrew
    add_anim Sandslash
    add_anim Sandshrew_Alola
    add_anim Sandslash_Alola
    add_anim Nidoran_F
    add_anim Nidorina
    add_anim Nidoqueen
    add_anim Nidoran_M
    add_anim Nidorino
    add_anim Nidoking
    add_anim Cleffa
    add_anim Clefairy
    add_anim Clefable
    add_anim Vulpix
    add_anim Ninetales
    add_anim Vulpix_Alola
    add_anim Ninetales_Alola
    add_anim Igglybuff
    add_anim Jigglypuff
    add_anim Wigglytuff
    add_anim Zubat
    add_anim Golbat
    add_anim Crobat
    add_anim Oddish
    add_anim Gloom
    add_anim Vileplume
    add_anim Bellossom
    add_anim Paras
    add_anim Parasect
    add_anim Venonat
    add_anim Venomoth
    add_anim Diglett
    add_anim Dugtrio
    add_anim Diglett_Alola
    add_anim Dugtrio_Alola
    add_anim Meowth
    add_anim Persian
    add_anim Meowth_Alola
    add_anim Persian_Alola
    add_anim Psyduck
    add_anim Golduck
    add_anim Mankey
    add_anim Primeape
    add_anim Growlithe
    add_anim Arcanine
    add_anim Poliwag
    add_anim Poliwhirl
    add_anim Poliwrath
    add_anim Politoed
    add_anim Abra
    add_anim Kadabra
    add_anim Alakazam
    add_anim Machop
    add_anim Machoke
    add_anim Machamp
    add_anim Bellsprout
    add_anim Weepinbell
    add_anim Victreebel
    add_anim Tentacool
    add_anim Tentacruel
    add_anim Geodude
    add_anim Graveler
    add_anim Golem
    add_anim Geodude_Alola
    add_anim Graveler_Alola
    add_anim Golem_Alola
    add_anim Ponyta
    add_anim Rapidash
    add_anim Slowpoke
    add_anim Slowbro
    add_anim Slowking
    add_anim Magnemite
    add_anim Magneton
    add_anim Magnezone
    add_anim FarfetchD
    add_anim Doduo
    add_anim Dodrio
    add_anim Seel
    add_anim Dewgong
    add_anim Grimer
    add_anim Muk
    add_anim Grimer_Alola
    add_anim Muk_Alola
    add_anim Shellder
    add_anim Cloyster
    add_anim Gastly
    add_anim Haunter
    add_anim Gengar
    add_anim Onix
    add_anim Steelix
    add_anim Drowzee
    add_anim Hypno
    add_anim Krabby
    add_anim Kingler
    add_anim Voltorb
    add_anim Electrode
    add_anim Exeggcute
    add_anim Exeggutor
    add_anim Exeggutor_Alola
    add_anim Cubone
    add_anim Marowak
    add_anim Marowak_Alola
    add_anim Tyrogue
    add_anim Hitmonlee
    add_anim Hitmonchan
    add_anim Hitmontop
    add_anim Lickitung
    add_anim Lickilicky
    add_anim Koffing
    add_anim Weezing
    add_anim Rhyhorn
    add_anim Rhydon
    add_anim Rhyperior
    add_anim Happiny
    add_anim Chansey
    add_anim Blissey
    add_anim Tangela
    add_anim Tangrowth
    add_anim Kangaskhan
    add_anim Horsea
    add_anim Seadra
    add_anim Kingdra
    add_anim Goldeen
    add_anim Seaking
    add_anim Staryu
    add_anim Starmie
    add_anim Mime_Jr
    add_anim MrMime
    add_anim Scyther
    add_anim Scizor
    add_anim Smoochum
    add_anim Jynx
    add_anim Elekid
    add_anim Electabuzz
    add_anim Electivire
    add_anim Magby
    add_anim Magmar
    add_anim Magmortar
    add_anim Pinsir
    add_anim Tauros
    add_anim Magikarp
    add_anim Gyarados
    add_anim Lapras
    add_anim Ditto
    add_anim Eevee
    add_anim Vaporeon
    add_anim Jolteon
    add_anim Flareon
    add_anim Espeon
    add_anim Umbreon
    add_anim Leafeon
    add_anim Glaceon
    add_anim Sylveon
    add_anim Porygon
    add_anim Porygon2
    add_anim PorygonZ
    add_anim Omanyte
    add_anim Omastar
    add_anim Kabuto
    add_anim Kabutops
    add_anim Aerodactyl
    add_anim Munchlax
    add_anim Snorlax
    add_anim Articuno
    add_anim Zapdos
    add_anim Moltres
    add_anim Dratini
    add_anim Dragonair
    add_anim Dragonite
    add_anim Mewtwo
    add_anim Mew
