KantoAnimationIdlePointers::
	add_idleanim Bulbasaur
	add_idleanim Ivysaur
	add_idleanim Venusaur
	add_idleanim Charmander
	add_idleanim Charmeleon
	add_idleanim Charizard
	add_idleanim Squirtle
	add_idleanim Wartortle
	add_idleanim Blastoise
	add_idleanim Caterpie
	add_idleanim Metapod
	add_idleanim Butterfree
	add_idleanim Weedle
	add_idleanim Kakuna
	add_idleanim Beedrill
	add_idleanim Pidgey
	add_idleanim Pidgeotto
	add_idleanim Pidgeot
	add_idleanim Rattata
	add_idleanim Raticate
	add_idleanim Spearow
	add_idleanim Fearow
	add_idleanim Ekans
	add_idleanim Arbok
	add_idleanim Pikachu
	add_idleanim Raichu
	add_idleanim Sandshrew
	add_idleanim Sandslash
	add_idleanim Nidoran_f
	add_idleanim Nidorina
	add_idleanim Nidoqueen
	add_idleanim Nidoran_m
	add_idleanim Nidorino
	add_idleanim Nidoking
	add_idleanim Clefairy
	add_idleanim Clefable
	add_idleanim Vulpix
	add_idleanim Ninetales
	add_idleanim Jigglypuff
	add_idleanim Wigglytuff
	add_idleanim Zubat
	add_idleanim Golbat
	add_idleanim Oddish
	add_idleanim Gloom
	add_idleanim Vileplume
	add_idleanim Paras
	add_idleanim Parasect
	add_idleanim Venonat
	add_idleanim Venomoth
	add_idleanim Diglett
	add_idleanim Dugtrio
	add_idleanim Meowth
	add_idleanim Persian
	add_idleanim Psyduck
	add_idleanim Golduck
	add_idleanim Mankey
	add_idleanim Primeape
	add_idleanim Growlithe
	add_idleanim Arcanine
	add_idleanim Poliwag
	add_idleanim Poliwhirl
	add_idleanim Poliwrath
	add_idleanim Abra
	add_idleanim Kadabra
	add_idleanim Alakazam
	add_idleanim Machop
	add_idleanim Machoke
	add_idleanim Machamp
	add_idleanim Bellsprout
	add_idleanim Weepinbell
	add_idleanim Victreebel
	add_idleanim Tentacool
	add_idleanim Tentacruel
	add_idleanim Geodude
	add_idleanim Graveler
	add_idleanim Golem
	add_idleanim Ponyta
	add_idleanim Rapidash
	add_idleanim Slowpoke
	add_idleanim Slowbro
	add_idleanim Magnemite
	add_idleanim Magneton
	add_idleanim Farfetch_d
	add_idleanim Doduo
	add_idleanim Dodrio
	add_idleanim Seel
	add_idleanim Dewgong
	add_idleanim Grimer
	add_idleanim Muk
	add_idleanim Shellder
	add_idleanim Cloyster
	add_idleanim Gastly
	add_idleanim Haunter
	add_idleanim Gengar
	add_idleanim Onix
	add_idleanim Drowzee
	add_idleanim Hypno
	add_idleanim Krabby
	add_idleanim Kingler
	add_idleanim Voltorb
	add_idleanim Electrode
	add_idleanim Exeggcute
	add_idleanim Exeggutor
	add_idleanim Cubone
	add_idleanim Marowak
	add_idleanim Hitmonlee
	add_idleanim Hitmonchan
	add_idleanim Lickitung
	add_idleanim Koffing
	add_idleanim Weezing
	add_idleanim Rhyhorn
	add_idleanim Rhydon
	add_idleanim Chansey
	add_idleanim Tangela
	add_idleanim Kangaskhan
	add_idleanim Horsea
	add_idleanim Seadra
	add_idleanim Goldeen
	add_idleanim Seaking
	add_idleanim Staryu
	add_idleanim Starmie
	add_idleanim Mr__mime
	add_idleanim Scyther
	add_idleanim Jynx
	add_idleanim Electabuzz
	add_idleanim Magmar
	add_idleanim Pinsir
	add_idleanim Tauros
	add_idleanim Magikarp
	add_idleanim Gyarados
	add_idleanim Lapras
	add_idleanim Ditto
	add_idleanim Eevee
	add_idleanim Vaporeon
	add_idleanim Jolteon
	add_idleanim Flareon
	add_idleanim Porygon
	add_idleanim Omanyte
	add_idleanim Omastar
	add_idleanim Kabuto
	add_idleanim Kabutops
	add_idleanim Aerodactyl
	add_idleanim Snorlax
	add_idleanim Articuno
	add_idleanim Zapdos
	add_idleanim Moltres
	add_idleanim Dratini
	add_idleanim Dragonair
	add_idleanim Dragonite
	add_idleanim Mewtwo
	add_idleanim Mew
