KantoFramesPointers::
    add_frames Bulbasaur
    add_frames Ivysaur
    add_frames Venusaur
    add_frames Charmander
    add_frames Charmeleon
    add_frames Charizard
    add_frames Squirtle
    add_frames Wartortle
    add_frames Blastoise
    add_frames Caterpie
    add_frames Metapod
    add_frames Butterfree
    add_frames Weedle
    add_frames Kakuna
    add_frames Beedrill
    add_frames Pidgey
    add_frames Pidgeotto
    add_frames Pidgeot
    add_frames Rattata
    add_frames Raticate
    add_frames Rattata_Alola
    add_frames Raticate_Alola
    add_frames Spearow
    add_frames Fearow
    add_frames Ekans
    add_frames Arbok
    add_frames Pichu
    add_frames Pikachu
    add_frames Raichu
    add_frames Raichu_Alola
    add_frames Sandshrew
    add_frames Sandslash
    add_frames Sandshrew_Alola
    add_frames Sandslash_Alola
    add_frames Nidoran_F
    add_frames Nidorina
    add_frames Nidoqueen
    add_frames Nidoran_M
    add_frames Nidorino
    add_frames Nidoking
    add_frames Cleffa
    add_frames Clefairy
    add_frames Clefable
    add_frames Vulpix
    add_frames Ninetales
    add_frames Vulpix_Alola
    add_frames Ninetales_Alola
    add_frames Igglybuff
    add_frames Jigglypuff
    add_frames Wigglytuff
    add_frames Zubat
    add_frames Golbat
    add_frames Crobat
    add_frames Oddish
    add_frames Gloom
    add_frames Vileplume
    add_frames Bellossom
    add_frames Paras
    add_frames Parasect
    add_frames Venonat
    add_frames Venomoth
    add_frames Diglett
    add_frames Dugtrio
    add_frames Diglett_Alola
    add_frames Dugtrio_Alola
    add_frames Meowth
    add_frames Persian
    add_frames Meowth_Alola
    add_frames Persian_Alola
    add_frames Psyduck
    add_frames Golduck
    add_frames Mankey
    add_frames Primeape
    add_frames Growlithe
    add_frames Arcanine
    add_frames Poliwag
    add_frames Poliwhirl
    add_frames Poliwrath
    add_frames Politoed
    add_frames Abra
    add_frames Kadabra
    add_frames Alakazam
    add_frames Machop
    add_frames Machoke
    add_frames Machamp
    add_frames Bellsprout
    add_frames Weepinbell
    add_frames Victreebel
    add_frames Tentacool
    add_frames Tentacruel
    add_frames Geodude
    add_frames Graveler
    add_frames Golem
    add_frames Geodude_Alola
    add_frames Graveler_Alola
    add_frames Golem_Alola
    add_frames Ponyta
    add_frames Rapidash
    add_frames Slowpoke
    add_frames Slowbro
    add_frames Slowking
    add_frames Magnemite
    add_frames Magneton
    add_frames Magnezone
    add_frames FarfetchD
    add_frames Doduo
    add_frames Dodrio
    add_frames Seel
    add_frames Dewgong
    add_frames Grimer
    add_frames Muk
    add_frames Grimer_Alola
    add_frames Muk_Alola
    add_frames Shellder
    add_frames Cloyster
    add_frames Gastly
    add_frames Haunter
    add_frames Gengar
    add_frames Onix
    add_frames Steelix
    add_frames Drowzee
    add_frames Hypno
    add_frames Krabby
    add_frames Kingler
    add_frames Voltorb
    add_frames Electrode
    add_frames Exeggcute
    add_frames Exeggutor
    add_frames Exeggutor_Alola
    add_frames Cubone
    add_frames Marowak
    add_frames Marowak_Alola
    add_frames Tyrogue
    add_frames Hitmonlee
    add_frames Hitmonchan
    add_frames Hitmontop
    add_frames Lickitung
    add_frames Lickilicky
    add_frames Koffing
    add_frames Weezing
    add_frames Rhyhorn
    add_frames Rhydon
    add_frames Rhyperior
    add_frames Happiny
    add_frames Chansey
    add_frames Blissey
    add_frames Tangela
    add_frames Tangrowth
    add_frames Kangaskhan
    add_frames Horsea
    add_frames Seadra
    add_frames Kingdra
    add_frames Goldeen
    add_frames Seaking
    add_frames Staryu
    add_frames Starmie
    add_frames Mime_Jr
    add_frames MrMime
    add_frames Scyther
    add_frames Scizor
    add_frames Smoochum
    add_frames Jynx
    add_frames Elekid
    add_frames Electabuzz
    add_frames Electivire
    add_frames Magby
    add_frames Magmar
    add_frames Magmortar
    add_frames Pinsir
    add_frames Tauros
    add_frames Magikarp
    add_frames Gyarados
    add_frames Lapras
    add_frames Ditto
    add_frames Eevee
    add_frames Vaporeon
    add_frames Jolteon
    add_frames Flareon
    add_frames Espeon
    add_frames Umbreon
    add_frames Leafeon
    add_frames Glaceon
    add_frames Sylveon
    add_frames Porygon
    add_frames Porygon2
    add_frames PorygonZ
    add_frames Omanyte
    add_frames Omastar
    add_frames Kabuto
    add_frames Kabutops
    add_frames Aerodactyl
    add_frames Munchlax
    add_frames Snorlax
    add_frames Articuno
    add_frames Zapdos
    add_frames Moltres
    add_frames Dratini
    add_frames Dragonair
    add_frames Dragonite
    add_frames Mewtwo
    add_frames Mew
