SinnohAnimationIdlePointers::
	add_idleanim Turtwig
	add_idleanim Grotle
	add_idleanim Torterra
	add_idleanim Chimchar
	add_idleanim Monferno
	add_idleanim Infernape
	add_idleanim Piplup
	add_idleanim Prinplup
	add_idleanim Emploeon
	add_idleanim Starly
	add_idleanim Staravia
	add_idleanim Staraptor
	add_idleanim Bidoof
	add_idleanim Bibarel
	add_idleanim Kricketot
	add_idleanim Kricketune
	add_idleanim Shinx
	add_idleanim Luxio
	add_idleanim Luxray
	add_idleanim Budew
	add_idleanim Roserade
	add_idleanim Crainidos
	add_idleanim Rampardos
	add_idleanim Sheildon
	add_idleanim Bastiodon
	add_idleanim Burmy
	add_idleanim Wormadam
	add_idleanim Mothim
	add_idleanim Combee
	add_idleanim Vespiquen
	add_idleanim Pachirisu
	add_idleanim Buizel
	add_idleanim Floatzel
	add_idleanim Cherubi
	add_idleanim Cherrim
	add_idleanim Shellos
	add_idleanim Gastrodon
	add_idleanim Ambipom
	add_idleanim Drifloon
	add_idleanim Drifblim
	add_idleanim Buneary
	add_idleanim Lopunny
	add_idleanim Mismagius
	add_idleanim Honchkrow
	add_idleanim Glameow
	add_idleanim Purugly
	add_idleanim Chingling
	add_idleanim Stunky
	add_idleanim Skuntank
	add_idleanim Bronzor
	add_idleanim Bronzong
	add_idleanim Bonsly
	add_idleanim Mime_jr
	add_idleanim Happiny
	add_idleanim Chatot
	add_idleanim Spiritomb
	add_idleanim Gible
	add_idleanim Gabite
	add_idleanim Garchomp
	add_idleanim Munchlax
	add_idleanim Riolu
	add_idleanim Lucario
	add_idleanim Hippopotas
	add_idleanim Hippowdon
	add_idleanim Skorupi
	add_idleanim Drapion
	add_idleanim Croagunk
	add_idleanim Toxicroak
	add_idleanim Carnivine
	add_idleanim Finneon
	add_idleanim Lumineon
	add_idleanim Mantyke
	add_idleanim Snover
	add_idleanim Abomasnow
	add_idleanim Weavile
	add_idleanim Magnezone
	add_idleanim Lickilicky
	add_idleanim Rhyperior
	add_idleanim Tangrowth
	add_idleanim Electivire
	add_idleanim Magmortar
	add_idleanim Togekiss
	add_idleanim Yanmega
	add_idleanim Leafeon
	add_idleanim Glaceon
	add_idleanim Gliscor
	add_idleanim Mamoswine
	add_idleanim Porygon_z
	add_idleanim Gallade
	add_idleanim Probopass
	add_idleanim Dusknoir
	add_idleanim Frosslass
	add_idleanim Rotom
	add_idleanim Uxie
	add_idleanim Mesprit
	add_idleanim Azelf
	add_idleanim Dialga
	add_idleanim Palkia
	add_idleanim Heatran
	add_idleanim Regigigas
	add_idleanim Giratina
	add_idleanim Cresselia
	add_idleanim Phione
	add_idleanim Manaphy
	add_idleanim Darkrai
	add_idleanim Shaymin
	add_idleanim Arceus
