SinnohBitmasksPointers::
	add_bitmasks Turtwig
	add_bitmasks Grotle
	add_bitmasks Torterra
	add_bitmasks Chimchar
	add_bitmasks Monferno
	add_bitmasks Infernape
	add_bitmasks Piplup
	add_bitmasks Prinplup
	add_bitmasks Emploeon
	add_bitmasks Starly
	add_bitmasks Staravia
	add_bitmasks Staraptor
	add_bitmasks Bidoof
	add_bitmasks Bibarel
	add_bitmasks Kricketot
	add_bitmasks Kricketune
	add_bitmasks Shinx
	add_bitmasks Luxio
	add_bitmasks Luxray
	add_bitmasks Budew
	add_bitmasks Roserade
	add_bitmasks Crainidos
	add_bitmasks Rampardos
	add_bitmasks Sheildon
	add_bitmasks Bastiodon
	add_bitmasks Burmy
	add_bitmasks Wormadam
	add_bitmasks Mothim
	add_bitmasks Combee
	add_bitmasks Vespiquen
	add_bitmasks Pachirisu
	add_bitmasks Buizel
	add_bitmasks Floatzel
	add_bitmasks Cherubi
	add_bitmasks Cherrim
	add_bitmasks Shellos
	add_bitmasks Gastrodon
	add_bitmasks Ambipom
	add_bitmasks Drifloon
	add_bitmasks Drifblim
	add_bitmasks Buneary
	add_bitmasks Lopunny
	add_bitmasks Mismagius
	add_bitmasks Honchkrow
	add_bitmasks Glameow
	add_bitmasks Purugly
	add_bitmasks Chingling
	add_bitmasks Stunky
	add_bitmasks Skuntank
	add_bitmasks Bronzor
	add_bitmasks Bronzong
	add_bitmasks Bonsly
	add_bitmasks Mime_jr
	add_bitmasks Happiny
	add_bitmasks Chatot
	add_bitmasks Spiritomb
	add_bitmasks Gible
	add_bitmasks Gabite
	add_bitmasks Garchomp
	add_bitmasks Munchlax
	add_bitmasks Riolu
	add_bitmasks Lucario
	add_bitmasks Hippopotas
	add_bitmasks Hippowdon
	add_bitmasks Skorupi
	add_bitmasks Drapion
	add_bitmasks Croagunk
	add_bitmasks Toxicroak
	add_bitmasks Carnivine
	add_bitmasks Finneon
	add_bitmasks Lumineon
	add_bitmasks Mantyke
	add_bitmasks Snover
	add_bitmasks Abomasnow
	add_bitmasks Weavile
	add_bitmasks Magnezone
	add_bitmasks Lickilicky
	add_bitmasks Rhyperior
	add_bitmasks Tangrowth
	add_bitmasks Electivire
	add_bitmasks Magmortar
	add_bitmasks Togekiss
	add_bitmasks Yanmega
	add_bitmasks Leafeon
	add_bitmasks Glaceon
	add_bitmasks Gliscor
	add_bitmasks Mamoswine
	add_bitmasks Porygon_z
	add_bitmasks Gallade
	add_bitmasks Probopass
	add_bitmasks Dusknoir
	add_bitmasks Froslass
	add_bitmasks Rotom
	add_bitmasks Uxie
	add_bitmasks Mesprit
	add_bitmasks Azelf
	add_bitmasks Dialga
	add_bitmasks Palkia
	add_bitmasks Heatran
	add_bitmasks Regigigas
	add_bitmasks Giratina
	add_bitmasks Cresselia
	add_bitmasks Phione
	add_bitmasks Manaphy
	add_bitmasks Darkrai
	add_bitmasks Shaymin
	add_bitmasks Arceus
