SinnohAnimationPointers::
	add_anim Turtwig
	add_anim Grotle
	add_anim Torterra
	add_anim Chimchar
	add_anim Monferno
	add_anim Infernape
	add_anim Piplup
	add_anim Prinplup
	add_anim Emploeon
	add_anim Starly
	add_anim Staravia
	add_anim Staraptor
	add_anim Bidoof
	add_anim Bibarel
	add_anim Kricketot
	add_anim Kricketune
	add_anim Shinx
	add_anim Luxio
	add_anim Luxray
	add_anim Budew
	add_anim Roserade
	add_anim Crainidos
	add_anim Rampardos
	add_anim Sheildon
	add_anim Bastiodon
	add_anim Burmy
	add_anim Wormadam
	add_anim Mothim
	add_anim Combee
	add_anim Vespiquen
	add_anim Pachirisu
	add_anim Buizel
	add_anim Floatzel
	add_anim Cherubi
	add_anim Cherrim
	add_anim Shellos
	add_anim Gastrodon
	add_anim Ambipom
	add_anim Drifloon
	add_anim Drifblim
	add_anim Buneary
	add_anim Lopunny
	add_anim Mismagius
	add_anim Honchkrow
	add_anim Glameow
	add_anim Purugly
	add_anim Chingling
	add_anim Stunky
	add_anim Skunktank
	add_anim Bronzor
	add_anim Bronzong
	add_anim Bonsly
	add_anim Mime_jr
	add_anim Happiny
	add_anim Chatot
	add_anim Spiritomb
	add_anim Gible
	add_anim Gabite
	add_anim Garchomp
	add_anim Munchlax
	add_anim Riolu
	add_anim Lucario
	add_anim Hippopotas
	add_anim Hippowdon
	add_anim Skorupi
	add_anim Drapion
	add_anim Croagunk
	add_anim Toxicroak
	add_anim Carnivine
	add_anim Finneon
	add_anim Lumineon
	add_anim Mantyke
	add_anim Snover
	add_anim Abomasnow
	add_anim Weavile
	add_anim Magnezone
	add_anim Lickilicky
	add_anim Rhyperior
	add_anim Tangrowth
	add_anim Electivire
	add_anim Magmortar
	add_anim Togekiss
	add_anim Yanmega
	add_anim Leafeon
	add_anim Glaceon
	add_anim Gliscor
	add_anim Mamoswine
	add_anim Porygon_z
	add_anim Gallade
	add_anim Probopass
	add_anim Dusknoir
	add_anim Frosslass
	add_anim Rotom
	add_anim Uxie
	add_anim Mesprit
	add_anim Azelf
	add_anim Dialga
	add_anim Palkia
	add_anim Heatran
	add_anim Regigigas
	add_anim Giratina
	add_anim Cresselia
	add_anim Phione
	add_anim Manaphy
	add_anim Darkrai
	add_anim Shaymin
	add_anim Arceus
