SinnohFramesPointers::
	add_frames Turtwig
	add_frames Grotle
	add_frames Torterra
	add_frames Chimchar
	add_frames Monferno
	add_frames Infernape
	add_frames Piplup
	add_frames Prinplup
	add_frames Emploeon
	add_frames Starly
	add_frames Staravia
	add_frames Staraptor
	add_frames Bidoof
	add_frames Bibarel
	add_frames Kricketot
	add_frames Kricketune
	add_frames Shinx
	add_frames Luxio
	add_frames Luxray
	add_frames Budew
	add_frames Roserade
	add_frames Crainidos
	add_frames Rampardos
	add_frames Sheildon
	add_frames Bastiodon
	add_frames Burmy
	add_frames Wormadam
	add_frames Mothim
	add_frames Combee
	add_frames Vespiquen
	add_frames Pachirisu
	add_frames Buizel
	add_frames Floatzel
	add_frames Cherubi
	add_frames Cherrim
	add_frames Shellos
	add_frames Gastrodon
	add_frames Ambipom
	add_frames Drifloon
	add_frames Drifblim
	add_frames Buneary
	add_frames Lopunny
	add_frames Mismagius
	add_frames Honchkrow
	add_frames Glameow
	add_frames Purugly
	add_frames Chingling
	add_frames Stunky
	add_frames Skuntank
	add_frames Bronzor
	add_frames Bronzong
	add_frames Bonsly
	add_frames Mime_jr
	add_frames Happiny
	add_frames Chatot
	add_frames Spiritomb
	add_frames Gible
	add_frames Gabite
	add_frames Garchomp
	add_frames Munchlax
	add_frames Riolu
	add_frames Lucario
	add_frames Hippopotas
	add_frames Hippowdon
	add_frames Skorupi
	add_frames Drapion
	add_frames Croagunk
	add_frames Toxicroak
	add_frames Carnivine
	add_frames Finneon
	add_frames Lumineon
	add_frames Mantyke
	add_frames Snover
	add_frames Abomasnow
	add_frames Weavile
	add_frames Magnezone
	add_frames Lickilicky
	add_frames Rhyperior
	add_frames Tangrowth
	add_frames Electivire
	add_frames Magmortar
	add_frames Togekiss
	add_frames Yanmega
	add_frames Leafeon
	add_frames Glaceon
	add_frames Gliscor
	add_frames Mamoswine
	add_frames Porygon_z
	add_frames Gallade
	add_frames Probopass
	add_frames Dusknoir
	add_frames Froslass
	add_frames Rotom
	add_frames Uxie
	add_frames Mesprit
	add_frames Azelf
	add_frames Dialga
	add_frames Palkia
	add_frames Heatran
	add_frames Regigigas
	add_frames Giratina
	add_frames Cresselia
	add_frames Phione
	add_frames Manaphy
	add_frames Darkrai
	add_frames Shaymin
	add_frames Arceus
