UnovaAnimationIdlePointers::
	add_idleanim Victini
	add_idleanim Snivy
	add_idleanim Servine
	add_idleanim Serperior
	add_idleanim Tepig
	add_idleanim Pignite
	add_idleanim Emboar
	add_idleanim Oshawott
	add_idleanim Dewott
	add_idleanim Samurott
	add_idleanim Patrat
	add_idleanim Watchog
	add_idleanim Lillipup
	add_idleanim Herdier
	add_idleanim Stoutland
	add_idleanim Purrloin
	add_idleanim Liepard
	add_idleanim Pansage
	add_idleanim Simisage
	add_idleanim Pansear
	add_idleanim Simisear
	add_idleanim Panpour
	add_idleanim Simipour
	add_idleanim Munna
	add_idleanim Musharna
	add_idleanim Pidove
	add_idleanim Tranquill
	add_idleanim Unfezant
	add_idleanim Blitzle
	add_idleanim Zebstrika
	add_idleanim Roggenrola
	add_idleanim Boldore
	add_idleanim Gigalith
	add_idleanim Woobat
	add_idleanim Swoobat
	add_idleanim Drilbur
	add_idleanim Excadrill
	add_idleanim Audino
	add_idleanim Timburr
	add_idleanim Gurdurr
	add_idleanim Conkeldurr
	add_idleanim Tympole
	add_idleanim Palpitoad
	add_idleanim Seismitoad
	add_idleanim Throh
	add_idleanim Sawk
	add_idleanim Sewaddle
	add_idleanim Swadloon
	add_idleanim Leavanny
	add_idleanim Venipede
	add_idleanim Whirlipede
	add_idleanim Scolipede
	add_idleanim Cottonee
	add_idleanim Whimsicott
	add_idleanim Petilil
	add_idleanim Lilligant
	add_idleanim Basculin
	add_idleanim Sandile
	add_idleanim Krokorok
	add_idleanim Krookodile
	add_idleanim Darumaka
	add_idleanim Darmanitan
	add_idleanim Maractus
	add_idleanim Dwebble
	add_idleanim Crustle
	add_idleanim Scraggy
	add_idleanim Scrafty
	add_idleanim Sigilyph
	add_idleanim Yamask
	add_idleanim Cofagrigus
	add_idleanim Tirtouga
	add_idleanim Carracosta
	add_idleanim Archen
	add_idleanim Archeops
	add_idleanim Trubbish
	add_idleanim Garbodor
	add_idleanim Zorua
	add_idleanim Zoroark
	add_idleanim Minccino
	add_idleanim Cinccino
	add_idleanim Gothita
	add_idleanim Gothorita
	add_idleanim Gothitelle
	add_idleanim Solosis
	add_idleanim Duosion
	add_idleanim Reuniclus
	add_idleanim Ducklett
	add_idleanim Swanna
	add_idleanim Vanillite
	add_idleanim Deerling
	add_idleanim Sawsbuck
	add_idleanim Emolga
	add_idleanim Karrablast
	add_idleanim Escavalier
	add_idleanim Foongus
	add_idleanim Amoonguss
	add_idleanim Frillish
	add_idleanim Jellicent
	add_idleanim Alomomola
	add_idleanim Joltik
	add_idleanim Galvantula
	add_idleanim Ferroseed
	add_idleanim Ferrothorn
	add_idleanim Klink
	add_idleanim Klang
	add_idleanim Klinklang
	add_idleanim Tynamo
	add_idleanim Eelektrik
	add_idleanim Eelektross
	add_idleanim Elgyem
	add_idleanim Beheeyem
	add_idleanim Litwick
	add_idleanim Lampent
	add_idleanim Chandelure
	add_idleanim Axew
	add_idleanim Fraxure
	add_idleanim Haxorus
	add_idleanim Cubchoo
	add_idleanim Beartic
	add_idleanim Cryogonal
	add_idleanim Shelmet
	add_idleanim Accelgor
	add_idleanim Stunfisk
	add_idleanim Mienfoo
	add_idleanim Mienshao
	add_idleanim Druddigon
	add_idleanim Golett
	add_idleanim Golurk
	add_idleanim Pawniard
	add_idleanim Bisharp
	add_idleanim Bouffalant
	add_idleanim Rufflet
	add_idleanim Braviary
	add_idleanim Vullaby
	add_idleanim Mandibuzz
	add_idleanim Heatmor
	add_idleanim Durant
	add_idleanim Deino
	add_idleanim Zweilous
	add_idleanim Hydreigon
	add_idleanim Larvesta
	add_idleanim Volcarona
	add_idleanim Cobalion
	add_idleanim Terrakion
	add_idleanim Virizion
	add_idleanim Tornadus
	add_idleanim Thundurus
	add_idleanim Reshiram
	add_idleanim Zekrom
	add_idleanim Landorus
	add_idleanim Kyurem
	add_idleanim Keldeo
	add_idleanim Meloetta
	add_idleanim Genesect
