UnovaFramesPointers::
	add_frames Victini
	add_frames Snivy
	add_frames Servine
	add_frames Serperior
	add_frames Tepig
	add_frames Pignite
	add_frames Emboar
	add_frames Oshawott
	add_frames Dewott
	add_frames Samurott
	add_frames Patrat
	add_frames Watchog
	add_frames Lillipup
	add_frames Herdier
	add_frames Stoutland
	add_frames Purrloin
	add_frames Liepard
	add_frames Pansage
	add_frames Simisage
	add_frames Pansear
	add_frames Simisear
	add_frames Panpour
	add_frames Simipour
	add_frames Munna
	add_frames Musharna
	add_frames Pidove
	add_frames Tranquil
	add_frames Unfezant
	add_frames Blitzle
	add_frames Zebstrika
	add_frames Roggenrola
	add_frames Boldore
	add_frames Gigalith
	add_frames Woobat
	add_frames Swoobat
	add_frames Drilbur
	add_frames Excadrill
	add_frames Audino
	add_frames Timburr
	add_frames Gurdurr
	add_frames Conkeldurr
	add_frames Tympole
	add_frames Palpitoad
	add_frames Seismitoad
	add_frames Throh
	add_frames Sawk
	add_frames Sewaddle
	add_frames Swadloon
	add_frames Leavanny
	add_frames Venipede
	add_frames Whirlipede
	add_frames Scolipede
	add_frames Cottonee
	add_frames Whimsicott
	add_frames Petilil
	add_frames Lilligant
	add_frames Basculin
	add_frames Sandile
	add_frames Krokorok
	add_frames Krookodile
	add_frames Darumaka
	add_frames Darmanitan
	add_frames Maractus
	add_frames Dwebble
	add_frames Crustle
	add_frames Scraggy
	add_frames Scrafty
	add_frames Sigilyph
	add_frames Yamask
	add_frames Cofagrigus
	add_frames Tirtouga
	add_frames Carracosta
	add_frames Archen
	add_frames Archeops
	add_frames Trubbish
	add_frames Garbodor
	add_frames Zorua
	add_frames Zoroark
	add_frames Minccino
	add_frames Cinccino
	add_frames Gothita
	add_frames Gothorita
	add_frames Gothitelle
	add_frames Solosis
	add_frames Duosion
	add_frames Reuniclus
	add_frames Ducklett
	add_frames Swanna
	add_frames Vanillite
	add_frames Deerling
	add_frames Sawsbuck
	add_frames Emolga
	add_frames Karrablast
	add_frames Escavalier
	add_frames Foongus
	add_frames Amoonguss
	add_frames Frillish
	add_frames Jellicent
	add_frames Alomomola
	add_frames Joltik
	add_frames Galvantula
	add_frames Ferroseed
	add_frames Ferrothorn
	add_frames Klink
	add_frames Klang
	add_frames Klinklang
	add_frames Tynamo
	add_frames Eelektrik
	add_frames Eelektross
	add_frames Elgyem
	add_frames Beheeyem
	add_frames Litwick
	add_frames Lampent
	add_frames Chandelure
	add_frames Axew
	add_frames Fraxure
	add_frames Haxorus
	add_frames Cubchoo
	add_frames Beartic
	add_frames Cryogonal
	add_frames Shelmet
	add_frames Accelgor
	add_frames Stunfisk
	add_frames Mienfoo
	add_frames Mienshao
	add_frames Druddigon
	add_frames Golett
	add_frames Golurk
	add_frames Pawniard
	add_frames Bisharp
	add_frames Bouffalant
	add_frames Rufflet
	add_frames Braviary
	add_frames Vullaby
	add_frames Mandibuzz
	add_frames Heatmor
	add_frames Durant
	add_frames Deino
	add_frames Zweilous
	add_frames Hydreigon
	add_frames Larvesta
	add_frames Volcarona
	add_frames Cobalion
	add_frames Terrakion
	add_frames Virizion
	add_frames Tornadus
	add_frames Thundurus
	add_frames Reshiram
	add_frames Zekrom
	add_frames Landorus
	add_frames Kyurem
	add_frames Keldeo
	add_frames Meloetta
	add_frames Genesect
