UnovaAnimationPointers::
	add_anim Victini
	add_anim Snivy
	add_anim Servine
	add_anim Serperior
	add_anim Tepig
	add_anim Pignite
	add_anim Emboar
	add_anim Oshawott
	add_anim Dewott
	add_anim Samurott
	add_anim Patrat
	add_anim Watchog
	add_anim Lillipup
	add_anim Herdier
	add_anim Stoutland
	add_anim Purrloin
	add_anim Liepard
	add_anim Pansage
	add_anim Simisage
	add_anim Pansear
	add_anim Simisear
	add_anim Panpour
	add_anim Simipour
	add_anim Munna
	add_anim Musharna
	add_anim Pidove
	add_anim Tranquil
	add_anim Unfezant
	add_anim Blitzle
	add_anim Zebstrika
	add_anim Roggenrola
	add_anim Boldore
	add_anim Gigalith
	add_anim Woobat
	add_anim Swoobat
	add_anim Drilbur
	add_anim Excadrill
	add_anim Audino
	add_anim Timburr
	add_anim Gurdurr
	add_anim Conkeldurr
	add_anim Tympole
	add_anim Palpitoad
	add_anim Seismitoad
	add_anim Throh
	add_anim Sawk
	add_anim Sewaddle
	add_anim Swadloon
	add_anim Leavanny
	add_anim Venipede
	add_anim Whirlipede
	add_anim Scolipede
	add_anim Cottonee
	add_anim Whimsicott
	add_anim Petilil
	add_anim Lilligant
	add_anim Basculin
	add_anim Sandile
	add_anim Krokorok
	add_anim Krookodile
	add_anim Darumaka
	add_anim Darmanitan
	add_anim Maractus
	add_anim Dwebble
	add_anim Crustle
	add_anim Scraggy
	add_anim Scrafty
	add_anim Sigilyph
	add_anim Yamask
	add_anim Cofagrigus
	add_anim Tirtouga
	add_anim Carracosta
	add_anim Archen
	add_anim Archeops
	add_anim Trubbish
	add_anim Garbodor
	add_anim Zorua
	add_anim Zoroark
	add_anim Minccino
	add_anim Cinccino
	add_anim Gothita
	add_anim Gothorita
	add_anim Gothitelle
	add_anim Solosis
	add_anim Duosion
	add_anim Reuniclus
	add_anim Ducklett
	add_anim Swanna
	add_anim Vanillite
	add_anim Deerling
	add_anim Sawsbuck
	add_anim Emolga
	add_anim Karrablast
	add_anim Escavalier
	add_anim Foongus
	add_anim Amoonguss
	add_anim Frillish
	add_anim Jellicent
	add_anim Alomomola
	add_anim Joltik
	add_anim Galvantula
	add_anim Ferroseed
	add_anim Ferrothorn
	add_anim Klink
	add_anim Klang
	add_anim Klinklang
	add_anim Tynamo
	add_anim Eelektrik
	add_anim Eelektross
	add_anim Elgyem
	add_anim Beheeyem
	add_anim Litwick
	add_anim Lampent
	add_anim Chandelure
	add_anim Axew
	add_anim Fraxure
	add_anim Haxorus
	add_anim Cubchoo
	add_anim Beartic
	add_anim Cryogonal
	add_anim Shelmet
	add_anim Accelgor
	add_anim Stunfisk
	add_anim Mienfoo
	add_anim Mienshao
	add_anim Druddigon
	add_anim Golett
	add_anim Golurk
	add_anim Pawniard
	add_anim Bisharp
	add_anim Bouffalant
	add_anim Rufflet
	add_anim Braviary
	add_anim Vullaby
	add_anim Mandibuzz
	add_anim Heatmor
	add_anim Durant
	add_anim Deino
	add_anim Zweilous
	add_anim Hydreigon
	add_anim Larvesta
	add_anim Volcarona
	add_anim Cobalion
	add_anim Terrakion
	add_anim Virizion
	add_anim Tornadus
	add_anim Thundurus
	add_anim Reshiram
	add_anim Zekrom
	add_anim Landorus
	add_anim Kyurem
	add_anim Keldeo
	add_anim Meloetta
	add_anim Genesect
