UnovaBitmasksPointers::
	add_bitmasks Victini
	add_bitmasks Snivy
	add_bitmasks Servine
	add_bitmasks Serperior
	add_bitmasks Tepig
	add_bitmasks Pignite
	add_bitmasks Emboar
	add_bitmasks Oshawott
	add_bitmasks Dewott
	add_bitmasks Samurott
	add_bitmasks Patrat
	add_bitmasks Watchog
	add_bitmasks Lillipup
	add_bitmasks Herdier
	add_bitmasks Stoutland
	add_bitmasks Purrloin
	add_bitmasks Liepard
	add_bitmasks Pansage
	add_bitmasks Simisage
	add_bitmasks Pansear
	add_bitmasks Simisear
	add_bitmasks Panpour
	add_bitmasks Simipour
	add_bitmasks Munna
	add_bitmasks Musharna
	add_bitmasks Pidove
	add_bitmasks Tranquil
	add_bitmasks Unfezant
	add_bitmasks Blitzle
	add_bitmasks Zebstrika
	add_bitmasks Roggenrola
	add_bitmasks Boldore
	add_bitmasks Gigalith
	add_bitmasks Woobat
	add_bitmasks Swoobat
	add_bitmasks Drilbur
	add_bitmasks Excadrill
	add_bitmasks Audino
	add_bitmasks Timburr
	add_bitmasks Gurdurr
	add_bitmasks Conkeldurr
	add_bitmasks Tympole
	add_bitmasks Palpitoad
	add_bitmasks Seismitoad
	add_bitmasks Throh
	add_bitmasks Sawk
	add_bitmasks Sewaddle
	add_bitmasks Swadloon
	add_bitmasks Leavanny
	add_bitmasks Venipede
	add_bitmasks Whirlipede
	add_bitmasks Scolipede
	add_bitmasks Cottonee
	add_bitmasks Whimsicott
	add_bitmasks Petilil
	add_bitmasks Lilligant
	add_bitmasks Basculin
	add_bitmasks Sandile
	add_bitmasks Krokorok
	add_bitmasks Krookodile
	add_bitmasks Darumaka
	add_bitmasks Darmanitan
	add_bitmasks Maractus
	add_bitmasks Dwebble
	add_bitmasks Crustle
	add_bitmasks Scraggy
	add_bitmasks Scrafty
	add_bitmasks Sigilyph
	add_bitmasks Yamask
	add_bitmasks Cofagrigus
	add_bitmasks Tirtouga
	add_bitmasks Carracosta
	add_bitmasks Archen
	add_bitmasks Archeops
	add_bitmasks Trubbish
	add_bitmasks Garbodor
	add_bitmasks Zorua
	add_bitmasks Zoroark
	add_bitmasks Minccino
	add_bitmasks Cinccino
	add_bitmasks Gothita
	add_bitmasks Gothorita
	add_bitmasks Gothitelle
	add_bitmasks Solosis
	add_bitmasks Duosion
	add_bitmasks Reuniclus
	add_bitmasks Ducklett
	add_bitmasks Swanna
	add_bitmasks Vanillite
	add_bitmasks Deerling
	add_bitmasks Sawsbuck
	add_bitmasks Emolga
	add_bitmasks Karrablast
	add_bitmasks Escavalier
	add_bitmasks Foongus
	add_bitmasks Amoonguss
	add_bitmasks Frillish
	add_bitmasks Jellicent
	add_bitmasks Alomomola
	add_bitmasks Joltik
	add_bitmasks Galvantula
	add_bitmasks Ferroseed
	add_bitmasks Ferrothorn
	add_bitmasks Klink
	add_bitmasks Klang
	add_bitmasks Klinklang
	add_bitmasks Tynamo
	add_bitmasks Eelektrik
	add_bitmasks Eelektross
	add_bitmasks Elgyem
	add_bitmasks Beheeyem
	add_bitmasks Litwick
	add_bitmasks Lampent
	add_bitmasks Chandelure
	add_bitmasks Axew
	add_bitmasks Fraxure
	add_bitmasks Haxorus
	add_bitmasks Cubchoo
	add_bitmasks Beartic
	add_bitmasks Cryogonal
	add_bitmasks Shelmet
	add_bitmasks Accelgor
	add_bitmasks Stunfisk
	add_bitmasks Mienfoo
	add_bitmasks Mienshao
	add_bitmasks Druddigon
	add_bitmasks Golett
	add_bitmasks Golurk
	add_bitmasks Pawniard
	add_bitmasks Bisharp
	add_bitmasks Bouffalant
	add_bitmasks Rufflet
	add_bitmasks Braviary
	add_bitmasks Vullaby
	add_bitmasks Mandibuzz
	add_bitmasks Heatmor
	add_bitmasks Durant
	add_bitmasks Deino
	add_bitmasks Zweilous
	add_bitmasks Hydreigon
	add_bitmasks Larvesta
	add_bitmasks Volcarona
	add_bitmasks Cobalion
	add_bitmasks Terrakion
	add_bitmasks Virizion
	add_bitmasks Tornadus
	add_bitmasks Thundurus
	add_bitmasks Reshiram
	add_bitmasks Zekrom
	add_bitmasks Landorus
	add_bitmasks Kyurem
	add_bitmasks Keldeo
	add_bitmasks Meloetta
	add_bitmasks Genesect
