SECTION "Hoenn Footprints", ROMX

HoennFootprints::
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/treecko.1bpp"
INCBIN "gfx/footprints/grovyle.1bpp"
INCBIN "gfx/footprints/sceptile.1bpp"
INCBIN "gfx/footprints/torchic.1bpp"
INCBIN "gfx/footprints/combusken.1bpp"
INCBIN "gfx/footprints/blaziken.1bpp"
INCBIN "gfx/footprints/mudkip.1bpp"
INCBIN "gfx/footprints/marshtomp.1bpp"
INCBIN "gfx/footprints/swampert.1bpp"
INCBIN "gfx/footprints/poochyena.1bpp"
INCBIN "gfx/footprints/mightyena.1bpp"
INCBIN "gfx/footprints/zigzagoon.1bpp"
INCBIN "gfx/footprints/linoone.1bpp"
INCBIN "gfx/footprints/wurmple.1bpp"
;INCBIN "gfx/footprints/silcoon.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/beautifly.1bpp"
;INCBIN "gfx/footprints/cascoon.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/dustox.1bpp"
INCBIN "gfx/footprints/lotad.1bpp"
INCBIN "gfx/footprints/lombre.1bpp"
INCBIN "gfx/footprints/ludicolo.1bpp"
INCBIN "gfx/footprints/seedot.1bpp"
INCBIN "gfx/footprints/nuzleaf.1bpp"
INCBIN "gfx/footprints/shiftry.1bpp"
INCBIN "gfx/footprints/taillow.1bpp"
INCBIN "gfx/footprints/swellow.1bpp"
INCBIN "gfx/footprints/wingull.1bpp"
INCBIN "gfx/footprints/pelipper.1bpp"
INCBIN "gfx/footprints/ralts.1bpp"
INCBIN "gfx/footprints/kirlia.1bpp"
INCBIN "gfx/footprints/gardevoir.1bpp"
INCBIN "gfx/footprints/surskit.1bpp"
;INCBIN "gfx/footprints/masquerain.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/shroomish.1bpp"
INCBIN "gfx/footprints/breloom.1bpp"
INCBIN "gfx/footprints/slakoth.1bpp"
INCBIN "gfx/footprints/vigoroth.1bpp"
INCBIN "gfx/footprints/slaking.1bpp"
INCBIN "gfx/footprints/nincada.1bpp"
INCBIN "gfx/footprints/ninjask.1bpp"
INCBIN "gfx/footprints/shedinja.1bpp"
INCBIN "gfx/footprints/whismur.1bpp"
INCBIN "gfx/footprints/loudred.1bpp"
INCBIN "gfx/footprints/exploud.1bpp"
INCBIN "gfx/footprints/makuhita.1bpp"
INCBIN "gfx/footprints/hariyama.1bpp"
INCBIN "gfx/footprints/nosepass.1bpp"
INCBIN "gfx/footprints/probopass.1bpp"
INCBIN "gfx/footprints/skitty.1bpp"
INCBIN "gfx/footprints/delcatty.1bpp"
INCBIN "gfx/footprints/sableye.1bpp"
INCBIN "gfx/footprints/mawile.1bpp"
INCBIN "gfx/footprints/aron.1bpp"
INCBIN "gfx/footprints/lairon.1bpp"
INCBIN "gfx/footprints/aggron.1bpp"
INCBIN "gfx/footprints/meditite.1bpp"
INCBIN "gfx/footprints/medicham.1bpp"
INCBIN "gfx/footprints/electrike.1bpp"
INCBIN "gfx/footprints/manectric.1bpp"
INCBIN "gfx/footprints/plusle.1bpp"
INCBIN "gfx/footprints/minun.1bpp"
INCBIN "gfx/footprints/volbeat.1bpp"
INCBIN "gfx/footprints/illumise.1bpp"
INCBIN "gfx/footprints/roselia.1bpp"
;INCBIN "gfx/footprints/gulpin.1bpp"
;INCBIN "gfx/footprints/swalot.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/carvanha.1bpp"
;INCBIN "gfx/footprints/sharpedo.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/wailmer.1bpp"
;INCBIN "gfx/footprints/wailord.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/numel.1bpp"
INCBIN "gfx/footprints/camerupt.1bpp"
INCBIN "gfx/footprints/torkoal.1bpp"
;INCBIN "gfx/footprints/spoink.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/grumpig.1bpp"
INCBIN "gfx/footprints/spinda.1bpp"
INCBIN "gfx/footprints/trapinch.1bpp"
INCBIN "gfx/footprints/vibrava.1bpp"
INCBIN "gfx/footprints/flygon.1bpp"
INCBIN "gfx/footprints/cacnea.1bpp"
INCBIN "gfx/footprints/cacturne.1bpp"
INCBIN "gfx/footprints/swablu.1bpp"
INCBIN "gfx/footprints/altaria.1bpp"
INCBIN "gfx/footprints/zangoose.1bpp"
INCBIN "gfx/footprints/seviper.1bpp"
;INCBIN "gfx/footprints/lunatone.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/solrock.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/barboach.1bpp"
;INCBIN "gfx/footprints/whiscash.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/corphish.1bpp"
INCBIN "gfx/footprints/crawdaunt.1bpp"
INCBIN "gfx/footprints/baltoy.1bpp"
INCBIN "gfx/footprints/claydol.1bpp"
INCBIN "gfx/footprints/lileep.1bpp"
INCBIN "gfx/footprints/cradily.1bpp"
INCBIN "gfx/footprints/anorith.1bpp"
INCBIN "gfx/footprints/armaldo.1bpp"
INCBIN "gfx/footprints/feebas.1bpp"
INCBIN "gfx/footprints/milotic.1bpp"
;INCBIN "gfx/footprints/castform.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/kecleon.1bpp"
;INCBIN "gfx/footprints/shuppet.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/banette.1bpp"
INCBIN "gfx/footprints/duskull.1bpp"
INCBIN "gfx/footprints/dusclops.1bpp"
INCBIN "gfx/footprints/tropius.1bpp"
;INCBIN "gfx/footprints/chimecho.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/absol.1bpp"
INCBIN "gfx/footprints/wynaut.1bpp"
INCBIN "gfx/footprints/snorunt.1bpp"
INCBIN "gfx/footprints/glalie.1bpp"
;INCBIN "gfx/footprints/spheal.1bpp"
;INCBIN "gfx/footprints/sealeo.1bpp"
;INCBIN "gfx/footprints/walrein.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/clamperl.1bpp"
;INCBIN "gfx/footprints/huntail.1bpp"
;INCBIN "gfx/footprints/gorebyss.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/relicanth.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/luvdisc.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/bagon.1bpp"
INCBIN "gfx/footprints/shelgon.1bpp"
INCBIN "gfx/footprints/salamence.1bpp"
INCBIN "gfx/footprints/beldum.1bpp"
INCBIN "gfx/footprints/metang.1bpp"
INCBIN "gfx/footprints/metagross.1bpp"
INCBIN "gfx/footprints/regirock.1bpp"
INCBIN "gfx/footprints/regice.1bpp"
INCBIN "gfx/footprints/registeel.1bpp"
INCBIN "gfx/footprints/latias.1bpp"
INCBIN "gfx/footprints/latios.1bpp"
INCBIN "gfx/footprints/kyogre.1bpp"
INCBIN "gfx/footprints/groudon.1bpp"
;INCBIN "gfx/footprints/rayquaza.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/jirachi.1bpp"
INCBIN "gfx/footprints/deoxys.1bpp"