
SECTION "Johto Footprints", ROMX

JohtoFootprints::
INCBIN "gfx/footprints/chikorita.1bpp" 
INCBIN "gfx/footprints/bayleef.1bpp" 
INCBIN "gfx/footprints/meganium.1bpp" 
INCBIN "gfx/footprints/cyndaquil.1bpp" 
INCBIN "gfx/footprints/quilava.1bpp" 
INCBIN "gfx/footprints/typhlosion.1bpp" 
INCBIN "gfx/footprints/totodile.1bpp" 
INCBIN "gfx/footprints/croconaw.1bpp" 
INCBIN "gfx/footprints/feraligatr.1bpp" 
INCBIN "gfx/footprints/sentret.1bpp" 
INCBIN "gfx/footprints/furret.1bpp" 
INCBIN "gfx/footprints/hoothoot.1bpp" 
INCBIN "gfx/footprints/noctowl.1bpp" 
INCBIN "gfx/footprints/ledyba.1bpp" 
INCBIN "gfx/footprints/ledian.1bpp" 
INCBIN "gfx/footprints/spinarak.1bpp" 
INCBIN "gfx/footprints/ariados.1bpp" 
INCBIN "gfx/footprints/chinchou.1bpp" 
INCBIN "gfx/footprints/lanturn.1bpp" 
INCBIN "gfx/footprints/togepi.1bpp" 
INCBIN "gfx/footprints/togetic.1bpp" 
INCBIN "gfx/footprints/togekiss.1bpp" 
INCBIN "gfx/footprints/natu.1bpp" 
INCBIN "gfx/footprints/xatu.1bpp" 
INCBIN "gfx/footprints/mareep.1bpp" 
INCBIN "gfx/footprints/flaaffy.1bpp" 
INCBIN "gfx/footprints/ampharos.1bpp"
INCBIN "gfx/footprints/azurill.1bpp" 
INCBIN "gfx/footprints/marill.1bpp" 
INCBIN "gfx/footprints/azumarill.1bpp" 
INCBIN "gfx/footprints/bonsly.1bpp" 
INCBIN "gfx/footprints/sudowoodo.1bpp" 
INCBIN "gfx/footprints/hoppip.1bpp" 
INCBIN "gfx/footprints/skiploom.1bpp" 
INCBIN "gfx/footprints/jumpluff.1bpp" 
INCBIN "gfx/footprints/aipom.1bpp" 
;INCBIN "gfx/footprints/ambipom.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy

INCBIN "gfx/footprints/sunkern.1bpp" 
INCBIN "gfx/footprints/sunflora.1bpp" 
INCBIN "gfx/footprints/yanma.1bpp" 
INCBIN "gfx/footprints/yanmega.1bpp" 
INCBIN "gfx/footprints/wooper.1bpp" 
INCBIN "gfx/footprints/quagsire.1bpp" 
INCBIN "gfx/footprints/murkrow.1bpp" 
;INCBIN "gfx/footprints/honchkrow.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy

INCBIN "gfx/footprints/misdreavus.1bpp" 
INCBIN "gfx/footprints/mismagius.1bpp" 
INCBIN "gfx/footprints/unown.1bpp" 
;INCBIN "gfx/footprints/wynaut.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy

INCBIN "gfx/footprints/wobbuffet.1bpp" 
INCBIN "gfx/footprints/girafarig.1bpp" 
INCBIN "gfx/footprints/pineco.1bpp" 
INCBIN "gfx/footprints/forretress.1bpp" 
INCBIN "gfx/footprints/dunsparce.1bpp" 
INCBIN "gfx/footprints/gligar.1bpp" 
;INCBIN "gfx/footprints/gliscor.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy

INCBIN "gfx/footprints/snubbull.1bpp" 
INCBIN "gfx/footprints/granbull.1bpp" 
INCBIN "gfx/footprints/qwilfish.1bpp" 
INCBIN "gfx/footprints/shuckle.1bpp" 
INCBIN "gfx/footprints/heracross.1bpp" 
INCBIN "gfx/footprints/sneasel.1bpp" 
INCBIN "gfx/footprints/weavile.1bpp" 
INCBIN "gfx/footprints/teddiursa.1bpp" 
INCBIN "gfx/footprints/ursaring.1bpp" 
INCBIN "gfx/footprints/slugma.1bpp" 
INCBIN "gfx/footprints/magcargo.1bpp" 
INCBIN "gfx/footprints/swinub.1bpp" 
INCBIN "gfx/footprints/piloswine.1bpp" 
INCBIN "gfx/footprints/mamoswine.1bpp" 
INCBIN "gfx/footprints/corsola.1bpp" 
INCBIN "gfx/footprints/remoraid.1bpp" 
INCBIN "gfx/footprints/octillery.1bpp" 
INCBIN "gfx/footprints/delibird.1bpp" 
;INCBIN "gfx/footprints/mantyke.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy

INCBIN "gfx/footprints/mantine.1bpp" 
INCBIN "gfx/footprints/skarmory.1bpp" 
INCBIN "gfx/footprints/houndour.1bpp" 
INCBIN "gfx/footprints/houndoom.1bpp" 
INCBIN "gfx/footprints/phanpy.1bpp" 
INCBIN "gfx/footprints/donphan.1bpp" 
INCBIN "gfx/footprints/stantler.1bpp" 
INCBIN "gfx/footprints/smeargle.1bpp" 
INCBIN "gfx/footprints/miltank.1bpp" 
INCBIN "gfx/footprints/raikou.1bpp" 
INCBIN "gfx/footprints/entei.1bpp" 
INCBIN "gfx/footprints/suicune.1bpp" 
INCBIN "gfx/footprints/larvitar.1bpp" 
INCBIN "gfx/footprints/pupitar.1bpp" 
INCBIN "gfx/footprints/tyranitar.1bpp" 
INCBIN "gfx/footprints/lugia.1bpp" 
INCBIN "gfx/footprints/ho_oh.1bpp" 
INCBIN "gfx/footprints/celebi.1bpp" 
