; Footprints are 2x2 tiles each, but are stored as a 16x64-tile image
; (32 rows of 8 footprints per row).
SECTION "Kanto Footprints", ROMX

KantoFootprints::
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/bulbasaur.1bpp" 
INCBIN "gfx/footprints/ivysaur.1bpp" 
INCBIN "gfx/footprints/venusaur.1bpp" 
INCBIN "gfx/footprints/charmander.1bpp" 
INCBIN "gfx/footprints/charmeleon.1bpp" 
INCBIN "gfx/footprints/charizard.1bpp" 
INCBIN "gfx/footprints/squirtle.1bpp" 
INCBIN "gfx/footprints/wartortle.1bpp" 
INCBIN "gfx/footprints/blastoise.1bpp" 
INCBIN "gfx/footprints/caterpie.1bpp" 
;INCBIN "gfx/footprints/metapod.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/butterfree.1bpp" 
INCBIN "gfx/footprints/weedle.1bpp" 
;INCBIN "gfx/footprints/kakuna.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/beedrill.1bpp" 
INCBIN "gfx/footprints/pidgey.1bpp" 
INCBIN "gfx/footprints/pidgeotto.1bpp" 
INCBIN "gfx/footprints/pidgeot.1bpp" 
INCBIN "gfx/footprints/rattata.1bpp" 
INCBIN "gfx/footprints/raticate.1bpp" 
INCBIN "gfx/footprints/spearow.1bpp" 
INCBIN "gfx/footprints/fearow.1bpp" 
;INCBIN "gfx/footprints/ekans.1bpp" 
;INCBIN "gfx/footprints/arbok.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/pichu.1bpp" 
INCBIN "gfx/footprints/pikachu.1bpp" 
INCBIN "gfx/footprints/raichu.1bpp" 
INCBIN "gfx/footprints/sandshrew.1bpp" 
INCBIN "gfx/footprints/sandslash.1bpp" 
INCBIN "gfx/footprints/nidoran_f.1bpp" 
INCBIN "gfx/footprints/nidorina.1bpp" 
INCBIN "gfx/footprints/nidoqueen.1bpp" 
INCBIN "gfx/footprints/nidoran_m.1bpp" 
INCBIN "gfx/footprints/nidorino.1bpp" 
INCBIN "gfx/footprints/nidoking.1bpp" 
INCBIN "gfx/footprints/cleffa.1bpp" 
INCBIN "gfx/footprints/clefairy.1bpp" 
INCBIN "gfx/footprints/clefable.1bpp" 
INCBIN "gfx/footprints/vulpix.1bpp" 
INCBIN "gfx/footprints/ninetales.1bpp" 
INCBIN "gfx/footprints/igglybuff.1bpp" 
INCBIN "gfx/footprints/jigglypuff.1bpp" 
INCBIN "gfx/footprints/wigglytuff.1bpp" 
;INCBIN "gfx/footprints/zubat.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/golbat.1bpp" 
;INCBIN "gfx/footprints/crobat.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/oddish.1bpp" 
INCBIN "gfx/footprints/gloom.1bpp" 
INCBIN "gfx/footprints/vileplume.1bpp" 
;INCBIN "gfx/footprints/bellossom.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/paras.1bpp" 
INCBIN "gfx/footprints/parasect.1bpp" 
INCBIN "gfx/footprints/venonat.1bpp" 
INCBIN "gfx/footprints/venomoth.1bpp" 
;INCBIN "gfx/footprints/diglett.1bpp" 
;INCBIN "gfx/footprints/dugtrio.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/meowth.1bpp" 
INCBIN "gfx/footprints/persian.1bpp" 
INCBIN "gfx/footprints/psyduck.1bpp" 
INCBIN "gfx/footprints/golduck.1bpp" 
INCBIN "gfx/footprints/mankey.1bpp" 
INCBIN "gfx/footprints/primeape.1bpp" 
INCBIN "gfx/footprints/growlithe.1bpp" 
INCBIN "gfx/footprints/arcanine.1bpp" 
INCBIN "gfx/footprints/poliwag.1bpp" 
INCBIN "gfx/footprints/poliwhirl.1bpp" 
INCBIN "gfx/footprints/poliwrath.1bpp" 
INCBIN "gfx/footprints/politoed.1bpp" 
INCBIN "gfx/footprints/abra.1bpp" 
INCBIN "gfx/footprints/kadabra.1bpp" 
INCBIN "gfx/footprints/alakazam.1bpp" 
INCBIN "gfx/footprints/machop.1bpp" 
INCBIN "gfx/footprints/machoke.1bpp" 
INCBIN "gfx/footprints/machamp.1bpp" 
INCBIN "gfx/footprints/bellsprout.1bpp" 
;INCBIN "gfx/footprints/weepinbell.1bpp" 
;INCBIN "gfx/footprints/victreebel.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
;INCBIN "gfx/footprints/tentacool.1bpp" 
;INCBIN "gfx/footprints/tentacruel.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
;INCBIN "gfx/footprints/geodude.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/graveler.1bpp" 
INCBIN "gfx/footprints/golem.1bpp" 
INCBIN "gfx/footprints/ponyta.1bpp" 
INCBIN "gfx/footprints/rapidash.1bpp" 
INCBIN "gfx/footprints/slowpoke.1bpp" 
INCBIN "gfx/footprints/slowbro.1bpp" 
INCBIN "gfx/footprints/slowking.1bpp" 
INCBIN "gfx/footprints/magnemite.1bpp" 
INCBIN "gfx/footprints/magneton.1bpp" 
INCBIN "gfx/footprints/magnezone.1bpp" 
INCBIN "gfx/footprints/farfetch_d.1bpp" 
INCBIN "gfx/footprints/doduo.1bpp" 
INCBIN "gfx/footprints/dodrio.1bpp" 
;INCBIN "gfx/footprints/seel.1bpp" 
;INCBIN "gfx/footprints/dewgong.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/grimer.1bpp" 
INCBIN "gfx/footprints/muk.1bpp" 
;INCBIN "gfx/footprints/shellder.1bpp" 
;INCBIN "gfx/footprints/cloyster.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/gastly.1bpp" 
INCBIN "gfx/footprints/haunter.1bpp" 
INCBIN "gfx/footprints/gengar.1bpp" 
;INCBIN "gfx/footprints/onix.1bpp" 
;INCBIN "gfx/footprints/steelix.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/256.1bpp"  ;blank
INCBIN "gfx/footprints/drowzee.1bpp" 
INCBIN "gfx/footprints/hypno.1bpp" 
INCBIN "gfx/footprints/krabby.1bpp" 
INCBIN "gfx/footprints/kingler.1bpp" 
;INCBIN "gfx/footprints/voltorb.1bpp" 
;INCBIN "gfx/footprints/electrode.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/exeggcute.1bpp" 
INCBIN "gfx/footprints/exeggutor.1bpp" 
INCBIN "gfx/footprints/cubone.1bpp" 
INCBIN "gfx/footprints/marowak.1bpp" 
INCBIN "gfx/footprints/tyrogue.1bpp" 
INCBIN "gfx/footprints/hitmonlee.1bpp" 
INCBIN "gfx/footprints/hitmonchan.1bpp" 
INCBIN "gfx/footprints/hitmontop.1bpp" 
INCBIN "gfx/footprints/lickitung.1bpp" 
INCBIN "gfx/footprints/lickilicky.1bpp"
;INCBIN "gfx/footprints/koffing.1bpp" 
;INCBIN "gfx/footprints/weezing.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/rhyhorn.1bpp" 
INCBIN "gfx/footprints/rhydon.1bpp" 
INCBIN "gfx/footprints/rhyperior.1bpp" 
INCBIN "gfx/footprints/happiny.1bpp" 
INCBIN "gfx/footprints/chansey.1bpp" 
INCBIN "gfx/footprints/blissey.1bpp" 
INCBIN "gfx/footprints/tangela.1bpp" 
INCBIN "gfx/footprints/tangrowth.1bpp" 
INCBIN "gfx/footprints/kangaskhan.1bpp" 
;INCBIN "gfx/footprints/horsea.1bpp" 
;INCBIN "gfx/footprints/seadra.1bpp" 
;INCBIN "gfx/footprints/kingdra.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/goldeen.1bpp" 
INCBIN "gfx/footprints/seaking.1bpp" 
INCBIN "gfx/footprints/staryu.1bpp" 
INCBIN "gfx/footprints/starmie.1bpp" 
INCBIN "gfx/footprints/mime_jr.1bpp" 
INCBIN "gfx/footprints/mr__mime.1bpp" 
INCBIN "gfx/footprints/scyther.1bpp" 
INCBIN "gfx/footprints/scizor.1bpp" 
INCBIN "gfx/footprints/smoochum.1bpp" 
;INCBIN "gfx/footprints/jynx.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/elekid.1bpp" 
INCBIN "gfx/footprints/electabuzz.1bpp" 
INCBIN "gfx/footprints/electivire.1bpp" 
INCBIN "gfx/footprints/magby.1bpp" 
INCBIN "gfx/footprints/magmar.1bpp" 
INCBIN "gfx/footprints/magmortar.1bpp" 
INCBIN "gfx/footprints/pinsir.1bpp" 
INCBIN "gfx/footprints/tauros.1bpp" 
;INCBIN "gfx/footprints/magikarp.1bpp" 
;INCBIN "gfx/footprints/gyarados.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/lapras.1bpp" 
INCBIN "gfx/footprints/ditto.1bpp" 
INCBIN "gfx/footprints/eevee.1bpp" 
INCBIN "gfx/footprints/vaporeon.1bpp" 
INCBIN "gfx/footprints/jolteon.1bpp" 
INCBIN "gfx/footprints/flareon.1bpp" 
INCBIN "gfx/footprints/espeon.1bpp" 
INCBIN "gfx/footprints/umbreon.1bpp" 
INCBIN "gfx/footprints/leafeon.1bpp" 
INCBIN "gfx/footprints/glaceon.1bpp" 
INCBIN "gfx/footprints/sylveon.1bpp" 
INCBIN "gfx/footprints/porygon.1bpp" 
INCBIN "gfx/footprints/porygon2.1bpp" 
INCBIN "gfx/footprints/porygon_z.1bpp" 
INCBIN "gfx/footprints/omanyte.1bpp" 
INCBIN "gfx/footprints/omastar.1bpp" 
INCBIN "gfx/footprints/kabuto.1bpp" 
INCBIN "gfx/footprints/kabutops.1bpp" 
INCBIN "gfx/footprints/aerodactyl.1bpp" 
INCBIN "gfx/footprints/munchlax.1bpp" 
INCBIN "gfx/footprints/snorlax.1bpp" 
INCBIN "gfx/footprints/articuno.1bpp" 
INCBIN "gfx/footprints/zapdos.1bpp" 
INCBIN "gfx/footprints/moltres.1bpp" 
;INCBIN "gfx/footprints/dratini.1bpp" 
;INCBIN "gfx/footprints/dragonair.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/dragonite.1bpp" 
INCBIN "gfx/footprints/mewtwo.1bpp" 
INCBIN "gfx/footprints/mew.1bpp" 
;INCBIN "gfx/footprints/madaamu.1bpp" 
INCBIN "gfx/footprints/256.1bpp"  ;dummy
