SECTION "Sinnoh Footprints", ROMX

SinnohFootprints::
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
