SECTION "Unova Footprints", ROMX

UnovaFootprints::
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/victini.1bpp"
INCBIN "gfx/footprints/snivy.1bpp"
INCBIN "gfx/footprints/servine.1bpp"
;INCBIN "gfx/footprints/serperior.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/tepig.1bpp"
INCBIN "gfx/footprints/pignite.1bpp"
INCBIN "gfx/footprints/emboar.1bpp"
INCBIN "gfx/footprints/oshawott.1bpp"
INCBIN "gfx/footprints/dewott.1bpp"
INCBIN "gfx/footprints/samurott.1bpp"
INCBIN "gfx/footprints/patrat.1bpp"
INCBIN "gfx/footprints/watchog.1bpp"
INCBIN "gfx/footprints/lillipup.1bpp"
INCBIN "gfx/footprints/herdier.1bpp"
INCBIN "gfx/footprints/stoutland.1bpp"
INCBIN "gfx/footprints/purrloin.1bpp"
INCBIN "gfx/footprints/liepard.1bpp"
INCBIN "gfx/footprints/pansage.1bpp"
INCBIN "gfx/footprints/simisage.1bpp"
INCBIN "gfx/footprints/pansear.1bpp"
INCBIN "gfx/footprints/simisear.1bpp"
INCBIN "gfx/footprints/panpour.1bpp"
INCBIN "gfx/footprints/simipour.1bpp"
INCBIN "gfx/footprints/munna.1bpp"
INCBIN "gfx/footprints/musharna.1bpp"
INCBIN "gfx/footprints/pidove.1bpp"
INCBIN "gfx/footprints/tranquill.1bpp"
INCBIN "gfx/footprints/unfezant.1bpp"
INCBIN "gfx/footprints/blitzle.1bpp"
INCBIN "gfx/footprints/zebstrika.1bpp"
INCBIN "gfx/footprints/roggenrola.1bpp"
INCBIN "gfx/footprints/boldore.1bpp"
INCBIN "gfx/footprints/gigalith.1bpp"
;INCBIN "gfx/footprints/woobat.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/swoobat.1bpp"
INCBIN "gfx/footprints/drilbur.1bpp"
INCBIN "gfx/footprints/excadrill.1bpp"
INCBIN "gfx/footprints/audino.1bpp"
INCBIN "gfx/footprints/timburr.1bpp"
INCBIN "gfx/footprints/gurdurr.1bpp"
INCBIN "gfx/footprints/conkeldurr.1bpp"
INCBIN "gfx/footprints/tympole.1bpp"
INCBIN "gfx/footprints/palpitoad.1bpp"
INCBIN "gfx/footprints/seismitoad.1bpp"
INCBIN "gfx/footprints/throh.1bpp"
INCBIN "gfx/footprints/sawk.1bpp"
INCBIN "gfx/footprints/sewaddle.1bpp"
;INCBIN "gfx/footprints/swadloon.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/leavanny.1bpp"
INCBIN "gfx/footprints/venipede.1bpp"
INCBIN "gfx/footprints/whirlipede.1bpp"
INCBIN "gfx/footprints/scolipede.1bpp"
INCBIN "gfx/footprints/cottonee.1bpp"
INCBIN "gfx/footprints/whimsicott.1bpp"
;INCBIN "gfx/footprints/petilil.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/lilligant.1bpp"
;INCBIN "gfx/footprints/basculin.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/sandile.1bpp"
INCBIN "gfx/footprints/krokorok.1bpp"
INCBIN "gfx/footprints/krookodile.1bpp"
INCBIN "gfx/footprints/darumaka.1bpp"
INCBIN "gfx/footprints/darmanitan.1bpp"
INCBIN "gfx/footprints/maractus.1bpp"
INCBIN "gfx/footprints/dwebble.1bpp"
INCBIN "gfx/footprints/crustle.1bpp"
INCBIN "gfx/footprints/scraggy.1bpp"
INCBIN "gfx/footprints/scrafty.1bpp"
INCBIN "gfx/footprints/sigilyph.1bpp"
INCBIN "gfx/footprints/yamask.1bpp"
INCBIN "gfx/footprints/cofagrigus.1bpp"
;INCBIN "gfx/footprints/tirtouga.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/carracosta.1bpp"
INCBIN "gfx/footprints/archen.1bpp"
INCBIN "gfx/footprints/archeops.1bpp"
INCBIN "gfx/footprints/trubbish.1bpp"
INCBIN "gfx/footprints/garbodor.1bpp"
INCBIN "gfx/footprints/zorua.1bpp"
INCBIN "gfx/footprints/zoroark.1bpp"
INCBIN "gfx/footprints/minccino.1bpp"
INCBIN "gfx/footprints/cinccino.1bpp"
INCBIN "gfx/footprints/gothita.1bpp"
INCBIN "gfx/footprints/gothorita.1bpp"
INCBIN "gfx/footprints/gothitelle.1bpp"
;INCBIN "gfx/footprints/solosis.1bpp"
;INCBIN "gfx/footprints/duosion.1bpp"
;INCBIN "gfx/footprints/reuniclus.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/ducklett.1bpp"
INCBIN "gfx/footprints/swanna.1bpp"
;INCBIN "gfx/footprints/vanillite.1bpp"
;INCBIN "gfx/footprints/vanillish.1bpp"
;INCBIN "gfx/footprints/vanilluxe.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/deerling.1bpp"
INCBIN "gfx/footprints/sawsbuck.1bpp"
INCBIN "gfx/footprints/emolga.1bpp"
INCBIN "gfx/footprints/karrablast.1bpp"
;INCBIN "gfx/footprints/escavalier.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/foongus.1bpp"
INCBIN "gfx/footprints/amoonguss.1bpp"
;INCBIN "gfx/footprints/frillish.1bpp"
;INCBIN "gfx/footprints/jellicent.1bpp"
;INCBIN "gfx/footprints/alomomola.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/joltik.1bpp"
INCBIN "gfx/footprints/galvantula.1bpp"
INCBIN "gfx/footprints/ferroseed.1bpp"
INCBIN "gfx/footprints/ferrothorn.1bpp"
;INCBIN "gfx/footprints/klink.1bpp"
;INCBIN "gfx/footprints/klang.1bpp"
;INCBIN "gfx/footprints/klinklang.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
;INCBIN "gfx/footprints/tynamo.1bpp"
;INCBIN "gfx/footprints/eelektrik.1bpp"
;INCBIN "gfx/footprints/eelektross.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/elgyem.1bpp"
INCBIN "gfx/footprints/beheeyem.1bpp"
INCBIN "gfx/footprints/litwick.1bpp"
INCBIN "gfx/footprints/lampent.1bpp"
INCBIN "gfx/footprints/chandelure.1bpp"
INCBIN "gfx/footprints/axew.1bpp"
INCBIN "gfx/footprints/fraxure.1bpp"
INCBIN "gfx/footprints/haxorus.1bpp"
INCBIN "gfx/footprints/cubchoo.1bpp"
INCBIN "gfx/footprints/beartic.1bpp"
INCBIN "gfx/footprints/cryogonal.1bpp"
INCBIN "gfx/footprints/shelmet.1bpp"
;INCBIN "gfx/footprints/accelgor.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/stunfisk.1bpp"
INCBIN "gfx/footprints/mienfoo.1bpp"
INCBIN "gfx/footprints/mienshao.1bpp"
INCBIN "gfx/footprints/druddigon.1bpp"
INCBIN "gfx/footprints/golett.1bpp"
INCBIN "gfx/footprints/golurk.1bpp"
INCBIN "gfx/footprints/pawniard.1bpp"
INCBIN "gfx/footprints/bisharp.1bpp"
INCBIN "gfx/footprints/bouffalant.1bpp"
INCBIN "gfx/footprints/rufflet.1bpp"
INCBIN "gfx/footprints/braviary.1bpp"
INCBIN "gfx/footprints/vullaby.1bpp"
INCBIN "gfx/footprints/mandibuzz.1bpp"
INCBIN "gfx/footprints/heatmor.1bpp"
INCBIN "gfx/footprints/durant.1bpp"
INCBIN "gfx/footprints/deino.1bpp"
INCBIN "gfx/footprints/zweilous.1bpp"
INCBIN "gfx/footprints/hydreigon.1bpp"
INCBIN "gfx/footprints/larvesta.1bpp"
;INCBIN "gfx/footprints/volcarona.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/cobalion.1bpp"
INCBIN "gfx/footprints/terrakion.1bpp"
INCBIN "gfx/footprints/virizion.1bpp"
;INCBIN "gfx/footprints/tornadus.1bpp"
;INCBIN "gfx/footprints/thundurus.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/reshiram.1bpp"
INCBIN "gfx/footprints/zekrom.1bpp"
;INCBIN "gfx/footprints/landorus.1bpp"
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/kyurem.1bpp"
INCBIN "gfx/footprints/keldeo.1bpp"
INCBIN "gfx/footprints/meloetta.1bpp"
INCBIN "gfx/footprints/genesect.1bpp"
