SECTION "Unova Footprints", ROMX

UnovaFootprints::
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
INCBIN "gfx/footprints/256.1bpp"  ;dummy
